// ============================================================
// THE HOUSE - Australian Political Strategy Game
// Policy definitions: 69 policies across 10 categories
// Based on real Australian policy debates and political landscape
// ============================================================

import { Policy } from '../types';

const POLICIES: Policy[] = [

  // ============================================================
  // TAXATION (7 policies)
  // ============================================================

  {
    id: 'tax_income_cut',
    name: 'Income Tax Cuts for Low and Middle Earners',
    shortName: 'Income Tax Cuts',
    description: 'Restructure income tax brackets to reduce the burden on workers earning under $120,000, funded by bracket creep savings.',
    category: 'taxation',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'neutral',
      market: 'favoured',
      interventionist: 'neutral',
    },
    budgetCost: -8,
    economicEffects: [
      { target: 'consumerConfidence', immediate: 4, perPeriod: 1.0, duration: 4, delay: 0, uncertainty: 0.2 },
      { target: 'gdpGrowth', immediate: 1, perPeriod: 0.5, duration: 4, delay: 1, uncertainty: 0.3 },
      { target: 'budgetBalance', immediate: -5, perPeriod: -1.0, duration: 4, delay: 0, uncertainty: 0.1 },
    ],
    voterImpacts: [
      { groupId: 'working_class', impact: 8 },
      { groupId: 'suburban_families', impact: 6 },
      { groupId: 'young_voters', impact: 4 },
      { groupId: 'business_owners', impact: -2 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'tax_corporate_cut',
    name: 'Corporate Tax Rate Reduction to 25%',
    shortName: 'Corporate Tax Cut',
    description: 'Lower the corporate tax rate from 30% to 25% to attract foreign investment and boost business competitiveness.',
    category: 'taxation',
    stanceTable: {
      progressive: 'opposed',
      conservative: 'favoured',
      market: 'favoured',
      interventionist: 'opposed',
    },
    budgetCost: -12,
    economicEffects: [
      { target: 'businessConfidence', immediate: 6, perPeriod: 1.5, duration: 5, delay: 0, uncertainty: 0.3 },
      { target: 'gdpGrowth', immediate: 1, perPeriod: 0.8, duration: 5, delay: 2, uncertainty: 0.4 },
      { target: 'budgetBalance', immediate: -8, perPeriod: -1.5, duration: 5, delay: 0, uncertainty: 0.2 },
      { target: 'unemployment', immediate: 0, perPeriod: -0.3, duration: 5, delay: 2, uncertainty: 0.4 },
    ],
    voterImpacts: [
      { groupId: 'business_owners', impact: 9 },
      { groupId: 'working_class', impact: -5 },
      { groupId: 'urban_professionals', impact: 2 },
      { groupId: 'public_sector', impact: -4 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'tax_gst_reform',
    name: 'GST Base Broadening and Compensation',
    shortName: 'GST Reform',
    description: 'Extend the GST to currently exempt goods and services while providing compensation payments to low-income households.',
    category: 'taxation',
    stanceTable: {
      progressive: 'opposed',
      conservative: 'favoured',
      market: 'favoured',
      interventionist: 'neutral',
    },
    budgetCost: 10,
    economicEffects: [
      { target: 'budgetBalance', immediate: 6, perPeriod: 2.0, duration: 5, delay: 1, uncertainty: 0.2 },
      { target: 'inflation', immediate: 2, perPeriod: 0.5, duration: 3, delay: 0, uncertainty: 0.3 },
      { target: 'consumerConfidence', immediate: -4, perPeriod: -0.5, duration: 3, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'working_class', impact: -6 },
      { groupId: 'retirees', impact: -4 },
      { groupId: 'business_owners', impact: 5 },
      { groupId: 'suburban_families', impact: -3 },
    ],
    implementationRounds: 2,
    isLandmark: false,
  },

  {
    id: 'tax_mining',
    name: 'Minerals Resource Rent Tax',
    shortName: 'Mining Tax',
    description: 'Impose a super-profits tax on mining companies extracting non-renewable resources, directing revenue to sovereign wealth fund.',
    category: 'taxation',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'opposed',
      market: 'opposed',
      interventionist: 'favoured',
    },
    budgetCost: 15,
    economicEffects: [
      { target: 'budgetBalance', immediate: 8, perPeriod: 2.5, duration: 6, delay: 1, uncertainty: 0.4 },
      { target: 'businessConfidence', immediate: -5, perPeriod: -1.0, duration: 4, delay: 0, uncertainty: 0.3 },
      { target: 'energy', immediate: -3, perPeriod: -0.5, duration: 4, delay: 1, uncertainty: 0.3 },
      { target: 'publicDebt', immediate: 0, perPeriod: -1.0, duration: 6, delay: 2, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'working_class', impact: 5 },
      { groupId: 'business_owners', impact: -8 },
      { groupId: 'rural_regional', impact: -6 },
      { groupId: 'urban_professionals', impact: 3 },
      { groupId: 'young_voters', impact: 4 },
    ],
    implementationRounds: 2,
    isLandmark: true,
  },

  {
    id: 'tax_capital_gains',
    name: 'Capital Gains Tax Discount Reform',
    shortName: 'CGT Reform',
    description: 'Reduce the capital gains tax discount from 50% to 25% to level the playing field between wage earners and investors.',
    category: 'taxation',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'opposed',
      market: 'opposed',
      interventionist: 'favoured',
    },
    budgetCost: 6,
    economicEffects: [
      { target: 'budgetBalance', immediate: 4, perPeriod: 1.0, duration: 5, delay: 1, uncertainty: 0.2 },
      { target: 'housing', immediate: -3, perPeriod: -0.8, duration: 4, delay: 1, uncertainty: 0.3 },
      { target: 'finance', immediate: -2, perPeriod: -0.5, duration: 3, delay: 0, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'business_owners', impact: -7 },
      { groupId: 'retirees', impact: -4 },
      { groupId: 'young_voters', impact: 6 },
      { groupId: 'working_class', impact: 3 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'tax_payroll_harmonise',
    name: 'National Payroll Tax Harmonisation',
    shortName: 'Payroll Tax Reform',
    description: 'Work with states to unify payroll tax thresholds and rates, reducing compliance costs for businesses operating across borders.',
    category: 'taxation',
    stanceTable: {
      progressive: 'neutral',
      conservative: 'favoured',
      market: 'favoured',
      interventionist: 'neutral',
    },
    budgetCost: -2,
    economicEffects: [
      { target: 'businessConfidence', immediate: 3, perPeriod: 0.8, duration: 4, delay: 1, uncertainty: 0.2 },
      { target: 'unemployment', immediate: 0, perPeriod: -0.4, duration: 4, delay: 2, uncertainty: 0.3 },
      { target: 'services', immediate: 1, perPeriod: 0.3, duration: 4, delay: 1, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'business_owners', impact: 7 },
      { groupId: 'working_class', impact: 2 },
      { groupId: 'urban_professionals', impact: 3 },
    ],
    implementationRounds: 2,
    isLandmark: false,
  },

  {
    id: 'tax_land_stamp_duty',
    name: 'Land Tax to Replace Stamp Duty',
    shortName: 'Land Tax Reform',
    description: 'Transition from stamp duty on property purchases to a broad-based annual land tax, improving housing mobility and revenue stability.',
    category: 'taxation',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'neutral',
      market: 'favoured',
      interventionist: 'neutral',
    },
    budgetCost: 2,
    economicEffects: [
      { target: 'housing', immediate: 3, perPeriod: 0.8, duration: 5, delay: 2, uncertainty: 0.3 },
      { target: 'budgetBalance', immediate: -3, perPeriod: 1.0, duration: 6, delay: 2, uncertainty: 0.3 },
      { target: 'consumerConfidence', immediate: -2, perPeriod: 0.5, duration: 4, delay: 1, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'young_voters', impact: 7 },
      { groupId: 'retirees', impact: -5 },
      { groupId: 'suburban_families', impact: 3 },
      { groupId: 'business_owners', impact: 2 },
    ],
    implementationRounds: 3,
    isLandmark: true,
  },

  // ============================================================
  // HEALTHCARE (7 policies)
  // ============================================================

  {
    id: 'health_bulk_billing',
    name: 'Medicare Bulk Billing Guarantee',
    shortName: 'Bulk Billing Fix',
    description: 'Triple the Medicare bulk billing incentive and mandate universal GP access to reverse the decline in bulk-billed consultations.',
    category: 'healthcare',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'opposed',
      market: 'opposed',
      interventionist: 'favoured',
    },
    budgetCost: -10,
    economicEffects: [
      { target: 'healthcare', immediate: 5, perPeriod: 1.5, duration: 5, delay: 1, uncertainty: 0.2 },
      { target: 'consumerConfidence', immediate: 4, perPeriod: 0.8, duration: 4, delay: 0, uncertainty: 0.2 },
      { target: 'budgetBalance', immediate: -6, perPeriod: -1.5, duration: 5, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'working_class', impact: 8 },
      { groupId: 'retirees', impact: 7 },
      { groupId: 'suburban_families', impact: 6 },
      { groupId: 'rural_regional', impact: 5 },
      { groupId: 'business_owners', impact: -3 },
    ],
    implementationRounds: 1,
    isLandmark: true,
  },

  {
    id: 'health_ndis_funding',
    name: 'NDIS Sustainable Funding Model',
    shortName: 'NDIS Reform',
    description: 'Restructure NDIS funding with independent assessments, price caps on providers, and a dedicated Medicare-style levy increase.',
    category: 'healthcare',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'neutral',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: -14,
    economicEffects: [
      { target: 'healthcare', immediate: 4, perPeriod: 1.2, duration: 6, delay: 1, uncertainty: 0.3 },
      { target: 'services', immediate: 3, perPeriod: 0.8, duration: 5, delay: 1, uncertainty: 0.2 },
      { target: 'budgetBalance', immediate: -7, perPeriod: -2.0, duration: 6, delay: 0, uncertainty: 0.3 },
      { target: 'unemployment', immediate: 0, perPeriod: -0.3, duration: 5, delay: 1, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'suburban_families', impact: 6 },
      { groupId: 'public_sector', impact: 5 },
      { groupId: 'working_class', impact: 4 },
      { groupId: 'business_owners', impact: -4 },
    ],
    implementationRounds: 2,
    isLandmark: true,
  },

  {
    id: 'health_mental',
    name: 'National Mental Health Strategy',
    shortName: 'Mental Health Plan',
    description: 'Fund 50 new headspace centres, expand Medicare mental health sessions to 20 per year, and create a national crisis hotline network.',
    category: 'healthcare',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'neutral',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: -6,
    economicEffects: [
      { target: 'healthcare', immediate: 3, perPeriod: 0.8, duration: 5, delay: 1, uncertainty: 0.2 },
      { target: 'consumerConfidence', immediate: 2, perPeriod: 0.5, duration: 4, delay: 1, uncertainty: 0.2 },
      { target: 'unemployment', immediate: 0, perPeriod: -0.2, duration: 5, delay: 2, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'young_voters', impact: 8 },
      { groupId: 'suburban_families', impact: 5 },
      { groupId: 'urban_professionals', impact: 4 },
      { groupId: 'working_class', impact: 3 },
    ],
    implementationRounds: 2,
    isLandmark: false,
  },

  {
    id: 'health_aged_care',
    name: 'Aged Care Quality and Safety Reform',
    shortName: 'Aged Care Reform',
    description: 'Implement Royal Commission recommendations: mandatory staffing ratios, registered nurses on-site 24/7, and increased home care packages.',
    category: 'healthcare',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'neutral',
      market: 'opposed',
      interventionist: 'favoured',
    },
    budgetCost: -11,
    economicEffects: [
      { target: 'healthcare', immediate: 4, perPeriod: 1.0, duration: 5, delay: 1, uncertainty: 0.2 },
      { target: 'services', immediate: 2, perPeriod: 0.5, duration: 4, delay: 1, uncertainty: 0.2 },
      { target: 'budgetBalance', immediate: -6, perPeriod: -1.5, duration: 5, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'retirees', impact: 9 },
      { groupId: 'suburban_families', impact: 5 },
      { groupId: 'public_sector', impact: 4 },
      { groupId: 'business_owners', impact: -3 },
    ],
    implementationRounds: 2,
    isLandmark: true,
  },

  {
    id: 'health_private_rebate',
    name: 'Private Health Insurance Rebate Increase',
    shortName: 'PHI Rebate Boost',
    description: 'Increase the private health insurance rebate by 10% to encourage private coverage and reduce pressure on public hospitals.',
    category: 'healthcare',
    stanceTable: {
      progressive: 'opposed',
      conservative: 'favoured',
      market: 'favoured',
      interventionist: 'opposed',
    },
    budgetCost: -5,
    economicEffects: [
      { target: 'healthcare', immediate: 1, perPeriod: 0.3, duration: 4, delay: 0, uncertainty: 0.3 },
      { target: 'finance', immediate: 2, perPeriod: 0.5, duration: 4, delay: 0, uncertainty: 0.2 },
      { target: 'budgetBalance', immediate: -3, perPeriod: -0.8, duration: 4, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'suburban_families', impact: 4 },
      { groupId: 'retirees', impact: 3 },
      { groupId: 'business_owners', impact: 4 },
      { groupId: 'working_class', impact: -3 },
      { groupId: 'young_voters', impact: -2 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'health_dental',
    name: 'Universal Dental Care Under Medicare',
    shortName: 'Medicare Dental',
    description: 'Extend Medicare to cover essential dental services including check-ups, fillings, and extractions for all Australians.',
    category: 'healthcare',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'opposed',
      market: 'opposed',
      interventionist: 'favoured',
    },
    budgetCost: -9,
    economicEffects: [
      { target: 'healthcare', immediate: 5, perPeriod: 1.2, duration: 5, delay: 1, uncertainty: 0.2 },
      { target: 'consumerConfidence', immediate: 3, perPeriod: 0.6, duration: 4, delay: 1, uncertainty: 0.2 },
      { target: 'budgetBalance', immediate: -5, perPeriod: -1.5, duration: 5, delay: 0, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'working_class', impact: 7 },
      { groupId: 'young_voters', impact: 6 },
      { groupId: 'retirees', impact: 5 },
      { groupId: 'suburban_families', impact: 4 },
      { groupId: 'business_owners', impact: -3 },
    ],
    implementationRounds: 2,
    isLandmark: true,
  },

  {
    id: 'health_pbs_expansion',
    name: 'Pharmaceutical Benefits Scheme Expansion',
    shortName: 'PBS Expansion',
    description: 'List 40 new medications on the PBS including cancer treatments, rare disease drugs, and reduce co-payments for concession holders.',
    category: 'healthcare',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'neutral',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: -7,
    economicEffects: [
      { target: 'healthcare', immediate: 3, perPeriod: 0.8, duration: 4, delay: 0, uncertainty: 0.2 },
      { target: 'consumerConfidence', immediate: 2, perPeriod: 0.4, duration: 4, delay: 0, uncertainty: 0.2 },
      { target: 'budgetBalance', immediate: -4, perPeriod: -1.0, duration: 4, delay: 0, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'retirees', impact: 7 },
      { groupId: 'working_class', impact: 5 },
      { groupId: 'suburban_families', impact: 4 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  // ============================================================
  // EDUCATION (7 policies)
  // ============================================================

  {
    id: 'edu_gonski',
    name: 'Gonski 3.0 - Needs-Based Schools Funding',
    shortName: 'Gonski 3.0',
    description: 'Fully fund public schools to 100% of the Schooling Resource Standard, with loadings for disadvantage, disability, and remoteness.',
    category: 'education',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'opposed',
      market: 'opposed',
      interventionist: 'favoured',
    },
    budgetCost: -12,
    economicEffects: [
      { target: 'education', immediate: 6, perPeriod: 1.5, duration: 6, delay: 1, uncertainty: 0.2 },
      { target: 'consumerConfidence', immediate: 3, perPeriod: 0.5, duration: 4, delay: 0, uncertainty: 0.2 },
      { target: 'budgetBalance', immediate: -7, perPeriod: -1.8, duration: 6, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'suburban_families', impact: 8 },
      { groupId: 'working_class', impact: 6 },
      { groupId: 'public_sector', impact: 7 },
      { groupId: 'rural_regional', impact: 5 },
      { groupId: 'business_owners', impact: -3 },
    ],
    implementationRounds: 2,
    isLandmark: true,
  },

  {
    id: 'edu_tafe',
    name: 'Fee-Free TAFE and Vocational Training',
    shortName: 'Fee-Free TAFE',
    description: 'Eliminate fees for priority TAFE courses in skills shortage areas including construction, aged care, IT, and clean energy.',
    category: 'education',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'neutral',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: -6,
    economicEffects: [
      { target: 'education', immediate: 4, perPeriod: 1.0, duration: 5, delay: 1, uncertainty: 0.2 },
      { target: 'unemployment', immediate: 0, perPeriod: -0.5, duration: 5, delay: 2, uncertainty: 0.3 },
      { target: 'manufacturing', immediate: 1, perPeriod: 0.4, duration: 5, delay: 2, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'working_class', impact: 7 },
      { groupId: 'young_voters', impact: 8 },
      { groupId: 'rural_regional', impact: 5 },
      { groupId: 'business_owners', impact: 3 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'edu_uni_free',
    name: 'University Fee-Free Places Expansion',
    shortName: 'Free Uni Places',
    description: 'Create 100,000 fee-free university places in nursing, teaching, engineering, and technology to address critical workforce shortages.',
    category: 'education',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'neutral',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: -8,
    economicEffects: [
      { target: 'education', immediate: 4, perPeriod: 1.2, duration: 5, delay: 1, uncertainty: 0.2 },
      { target: 'technology', immediate: 1, perPeriod: 0.5, duration: 5, delay: 2, uncertainty: 0.3 },
      { target: 'unemployment', immediate: 0, perPeriod: -0.3, duration: 5, delay: 3, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'young_voters', impact: 9 },
      { groupId: 'urban_professionals', impact: 4 },
      { groupId: 'suburban_families', impact: 3 },
      { groupId: 'public_sector', impact: 4 },
    ],
    implementationRounds: 2,
    isLandmark: false,
  },

  {
    id: 'edu_hecs_reform',
    name: 'HECS-HELP Student Debt Reform',
    shortName: 'HECS Reform',
    description: 'Cap HECS indexation at CPI or wages growth (whichever lower), raise the repayment threshold, and write off debts after 20 years.',
    category: 'education',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'opposed',
      market: 'opposed',
      interventionist: 'favoured',
    },
    budgetCost: -5,
    economicEffects: [
      { target: 'education', immediate: 2, perPeriod: 0.5, duration: 4, delay: 0, uncertainty: 0.2 },
      { target: 'consumerConfidence', immediate: 3, perPeriod: 0.6, duration: 4, delay: 0, uncertainty: 0.2 },
      { target: 'budgetBalance', immediate: -3, perPeriod: -0.8, duration: 5, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'young_voters', impact: 9 },
      { groupId: 'urban_professionals', impact: 5 },
      { groupId: 'retirees', impact: -2 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'edu_research',
    name: 'National Research and Innovation Fund',
    shortName: 'Research Fund',
    description: 'Boost ARC and CSIRO funding by $3 billion, establish a national research commercialisation program, and restore university block grants.',
    category: 'education',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'neutral',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: -7,
    economicEffects: [
      { target: 'technology', immediate: 4, perPeriod: 1.2, duration: 6, delay: 2, uncertainty: 0.3 },
      { target: 'education', immediate: 3, perPeriod: 0.8, duration: 5, delay: 1, uncertainty: 0.2 },
      { target: 'gdpGrowth', immediate: 0, perPeriod: 0.5, duration: 6, delay: 3, uncertainty: 0.4 },
    ],
    voterImpacts: [
      { groupId: 'urban_professionals', impact: 6 },
      { groupId: 'public_sector', impact: 5 },
      { groupId: 'young_voters', impact: 4 },
      { groupId: 'business_owners', impact: 2 },
    ],
    implementationRounds: 2,
    isLandmark: false,
  },

  {
    id: 'edu_childcare',
    name: 'Universal Childcare Subsidy',
    shortName: 'Universal Childcare',
    description: 'Increase the childcare subsidy to 90% for families earning under $80,000 and extend to all families regardless of activity test.',
    category: 'education',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'neutral',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: -11,
    economicEffects: [
      { target: 'education', immediate: 3, perPeriod: 0.8, duration: 5, delay: 1, uncertainty: 0.2 },
      { target: 'unemployment', immediate: -1, perPeriod: -0.5, duration: 5, delay: 1, uncertainty: 0.3 },
      { target: 'gdpGrowth', immediate: 1, perPeriod: 0.6, duration: 5, delay: 1, uncertainty: 0.3 },
      { target: 'consumerConfidence', immediate: 3, perPeriod: 0.5, duration: 4, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'suburban_families', impact: 9 },
      { groupId: 'working_class', impact: 6 },
      { groupId: 'young_voters', impact: 5 },
      { groupId: 'urban_professionals', impact: 5 },
      { groupId: 'business_owners', impact: -2 },
    ],
    implementationRounds: 1,
    isLandmark: true,
  },

  {
    id: 'edu_digital_stem',
    name: 'Digital Skills and STEM in Schools',
    shortName: 'STEM Initiative',
    description: 'Mandate coding and computational thinking from Year 3, fund school tech labs, and train 5,000 specialist STEM teachers.',
    category: 'education',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'favoured',
      market: 'favoured',
      interventionist: 'neutral',
    },
    budgetCost: -4,
    economicEffects: [
      { target: 'education', immediate: 2, perPeriod: 0.6, duration: 5, delay: 1, uncertainty: 0.2 },
      { target: 'technology', immediate: 1, perPeriod: 0.8, duration: 6, delay: 3, uncertainty: 0.4 },
    ],
    voterImpacts: [
      { groupId: 'suburban_families', impact: 5 },
      { groupId: 'urban_professionals', impact: 4 },
      { groupId: 'business_owners', impact: 4 },
      { groupId: 'young_voters', impact: 3 },
    ],
    implementationRounds: 2,
    isLandmark: false,
  },

  // ============================================================
  // HOUSING (7 policies)
  // ============================================================

  {
    id: 'housing_social_build',
    name: 'Social and Affordable Housing Fund',
    shortName: 'Social Housing Fund',
    description: 'Invest $10 billion in a Housing Australia Future Fund to build 30,000 social and affordable homes over five years.',
    category: 'housing',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'opposed',
      market: 'opposed',
      interventionist: 'favoured',
    },
    budgetCost: -15,
    economicEffects: [
      { target: 'housing', immediate: 6, perPeriod: 2.0, duration: 6, delay: 2, uncertainty: 0.3 },
      { target: 'unemployment', immediate: -2, perPeriod: -0.6, duration: 5, delay: 1, uncertainty: 0.2 },
      { target: 'gdpGrowth', immediate: 2, perPeriod: 0.8, duration: 5, delay: 1, uncertainty: 0.3 },
      { target: 'budgetBalance', immediate: -8, perPeriod: -2.0, duration: 6, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'working_class', impact: 8 },
      { groupId: 'young_voters', impact: 7 },
      { groupId: 'urban_professionals', impact: 3 },
      { groupId: 'business_owners', impact: -4 },
      { groupId: 'public_sector', impact: 4 },
    ],
    implementationRounds: 3,
    isLandmark: true,
  },

  {
    id: 'housing_neg_gearing',
    name: 'Negative Gearing Reform',
    shortName: 'End Neg Gearing',
    description: 'Limit negative gearing to new housing stock only, grandfathering existing arrangements, to reduce speculation and improve affordability.',
    category: 'housing',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'opposed',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: 8,
    economicEffects: [
      { target: 'housing', immediate: 4, perPeriod: 1.2, duration: 5, delay: 1, uncertainty: 0.4 },
      { target: 'budgetBalance', immediate: 5, perPeriod: 1.5, duration: 5, delay: 1, uncertainty: 0.2 },
      { target: 'finance', immediate: -3, perPeriod: -0.5, duration: 3, delay: 0, uncertainty: 0.3 },
      { target: 'consumerConfidence', immediate: -2, perPeriod: 0.3, duration: 4, delay: 1, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'young_voters', impact: 8 },
      { groupId: 'working_class', impact: 4 },
      { groupId: 'retirees', impact: -6 },
      { groupId: 'business_owners', impact: -5 },
      { groupId: 'suburban_families', impact: -2 },
    ],
    implementationRounds: 2,
    isLandmark: true,
  },

  {
    id: 'housing_rent_control',
    name: 'National Rent Stabilisation Framework',
    shortName: 'Rent Controls',
    description: 'Cap annual rent increases at CPI + 2%, establish a national rental tribunal, and fund renter advocacy services.',
    category: 'housing',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'opposed',
      market: 'opposed',
      interventionist: 'favoured',
    },
    budgetCost: -2,
    economicEffects: [
      { target: 'housing', immediate: 2, perPeriod: 0.5, duration: 4, delay: 0, uncertainty: 0.3 },
      { target: 'inflation', immediate: -1, perPeriod: -0.3, duration: 3, delay: 0, uncertainty: 0.2 },
      { target: 'businessConfidence', immediate: -3, perPeriod: -0.5, duration: 3, delay: 0, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'young_voters', impact: 7 },
      { groupId: 'working_class', impact: 6 },
      { groupId: 'urban_professionals', impact: 3 },
      { groupId: 'business_owners', impact: -7 },
      { groupId: 'retirees', impact: -3 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'housing_first_home',
    name: 'First Home Buyer Guarantee Expansion',
    shortName: 'First Home Boost',
    description: 'Expand the Home Guarantee Scheme to 50,000 places per year with 5% deposits, and increase the price caps in major cities.',
    category: 'housing',
    stanceTable: {
      progressive: 'neutral',
      conservative: 'favoured',
      market: 'favoured',
      interventionist: 'neutral',
    },
    budgetCost: -4,
    economicEffects: [
      { target: 'housing', immediate: 2, perPeriod: 0.6, duration: 4, delay: 0, uncertainty: 0.3 },
      { target: 'finance', immediate: 2, perPeriod: 0.4, duration: 3, delay: 0, uncertainty: 0.2 },
      { target: 'consumerConfidence', immediate: 3, perPeriod: 0.5, duration: 3, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'young_voters', impact: 6 },
      { groupId: 'suburban_families', impact: 5 },
      { groupId: 'working_class', impact: 3 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'housing_foreign_ban',
    name: 'Foreign Buyer Residential Investment Ban',
    shortName: 'Foreign Buyer Ban',
    description: 'Ban foreign non-residents from purchasing existing residential property and impose higher surcharges on new property purchases.',
    category: 'housing',
    stanceTable: {
      progressive: 'neutral',
      conservative: 'favoured',
      market: 'opposed',
      interventionist: 'favoured',
    },
    budgetCost: 1,
    economicEffects: [
      { target: 'housing', immediate: 2, perPeriod: 0.5, duration: 4, delay: 0, uncertainty: 0.4 },
      { target: 'finance', immediate: -2, perPeriod: -0.3, duration: 3, delay: 0, uncertainty: 0.3 },
      { target: 'businessConfidence', immediate: -1, perPeriod: -0.2, duration: 3, delay: 0, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'young_voters', impact: 5 },
      { groupId: 'working_class', impact: 4 },
      { groupId: 'suburban_families', impact: 3 },
      { groupId: 'business_owners', impact: -3 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'housing_public_renewal',
    name: 'Public Housing Estate Renewal Program',
    shortName: 'Public Housing Renewal',
    description: 'Rebuild and modernise aging public housing estates in major cities, increasing density and improving living standards for 50,000 tenants.',
    category: 'housing',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'neutral',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: -10,
    economicEffects: [
      { target: 'housing', immediate: 4, perPeriod: 1.0, duration: 5, delay: 2, uncertainty: 0.3 },
      { target: 'unemployment', immediate: -1, perPeriod: -0.4, duration: 4, delay: 1, uncertainty: 0.2 },
      { target: 'gdpGrowth', immediate: 1, perPeriod: 0.5, duration: 4, delay: 1, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'working_class', impact: 7 },
      { groupId: 'urban_professionals', impact: 2 },
      { groupId: 'public_sector', impact: 4 },
      { groupId: 'young_voters', impact: 3 },
    ],
    implementationRounds: 3,
    isLandmark: false,
  },

  {
    id: 'housing_help_to_buy',
    name: 'Help to Buy Shared Equity Scheme',
    shortName: 'Help to Buy',
    description: 'Government takes up to 40% equity in new homes (30% existing) for low-to-middle income earners, repaid when the property is sold.',
    category: 'housing',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'neutral',
      market: 'opposed',
      interventionist: 'favoured',
    },
    budgetCost: -6,
    economicEffects: [
      { target: 'housing', immediate: 3, perPeriod: 0.8, duration: 5, delay: 1, uncertainty: 0.3 },
      { target: 'consumerConfidence', immediate: 2, perPeriod: 0.4, duration: 4, delay: 0, uncertainty: 0.2 },
      { target: 'budgetBalance', immediate: -4, perPeriod: -0.8, duration: 5, delay: 0, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'young_voters', impact: 7 },
      { groupId: 'working_class', impact: 5 },
      { groupId: 'suburban_families', impact: 4 },
      { groupId: 'business_owners', impact: -2 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  // ============================================================
  // CLIMATE (7 policies)
  // ============================================================

  {
    id: 'climate_ets',
    name: 'Safeguard Mechanism Emissions Trading Scheme',
    shortName: 'Emissions Trading',
    description: 'Expand the safeguard mechanism into a comprehensive cap-and-trade emissions trading scheme covering the top 500 industrial emitters.',
    category: 'climate',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'opposed',
      market: 'favoured',
      interventionist: 'neutral',
    },
    budgetCost: 5,
    economicEffects: [
      { target: 'energy', immediate: -4, perPeriod: -0.8, duration: 5, delay: 1, uncertainty: 0.3 },
      { target: 'budgetBalance', immediate: 3, perPeriod: 1.0, duration: 5, delay: 1, uncertainty: 0.3 },
      { target: 'businessConfidence', immediate: -3, perPeriod: -0.5, duration: 3, delay: 0, uncertainty: 0.3 },
      { target: 'manufacturing', immediate: -2, perPeriod: -0.4, duration: 4, delay: 1, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'young_voters', impact: 7 },
      { groupId: 'urban_professionals', impact: 5 },
      { groupId: 'business_owners', impact: -6 },
      { groupId: 'rural_regional', impact: -5 },
      { groupId: 'working_class', impact: -2 },
    ],
    implementationRounds: 2,
    isLandmark: true,
  },

  {
    id: 'climate_renewable_target',
    name: 'Renewable Energy Target 82% by 2030',
    shortName: '82% Renewables',
    description: 'Legislate an 82% renewable electricity target with Capacity Investment Scheme auctions, rewired transmission, and community battery grants.',
    category: 'climate',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'opposed',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: -9,
    economicEffects: [
      { target: 'energy', immediate: 3, perPeriod: 1.5, duration: 6, delay: 2, uncertainty: 0.3 },
      { target: 'unemployment', immediate: -1, perPeriod: -0.4, duration: 5, delay: 1, uncertainty: 0.3 },
      { target: 'technology', immediate: 2, perPeriod: 0.8, duration: 5, delay: 1, uncertainty: 0.3 },
      { target: 'manufacturing', immediate: -1, perPeriod: 0.3, duration: 5, delay: 2, uncertainty: 0.4 },
    ],
    voterImpacts: [
      { groupId: 'young_voters', impact: 8 },
      { groupId: 'urban_professionals', impact: 5 },
      { groupId: 'rural_regional', impact: 3 },
      { groupId: 'business_owners', impact: -3 },
      { groupId: 'working_class', impact: -1 },
    ],
    implementationRounds: 2,
    isLandmark: true,
  },

  {
    id: 'climate_nuclear',
    name: 'Nuclear Energy Investigation and Pathway',
    shortName: 'Nuclear Energy',
    description: 'Lift the moratorium on nuclear power, commission feasibility studies for small modular reactors at retired coal plant sites.',
    category: 'climate',
    stanceTable: {
      progressive: 'opposed',
      conservative: 'favoured',
      market: 'favoured',
      interventionist: 'neutral',
    },
    budgetCost: -8,
    economicEffects: [
      { target: 'energy', immediate: 0, perPeriod: 1.0, duration: 8, delay: 3, uncertainty: 0.5 },
      { target: 'technology', immediate: 2, perPeriod: 0.5, duration: 6, delay: 2, uncertainty: 0.4 },
      { target: 'businessConfidence', immediate: 2, perPeriod: 0.3, duration: 4, delay: 0, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'business_owners', impact: 5 },
      { groupId: 'rural_regional', impact: 3 },
      { groupId: 'young_voters', impact: -5 },
      { groupId: 'urban_professionals', impact: -3 },
    ],
    implementationRounds: 3,
    isLandmark: true,
  },

  {
    id: 'climate_ev_subsidy',
    name: 'Electric Vehicle National Strategy',
    shortName: 'EV Subsidies',
    description: 'Provide $3,000 rebates on EVs under $68,000, mandate fuel efficiency standards, and fund a national fast-charging network.',
    category: 'climate',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'neutral',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: -5,
    economicEffects: [
      { target: 'energy', immediate: 1, perPeriod: 0.6, duration: 5, delay: 1, uncertainty: 0.3 },
      { target: 'technology', immediate: 2, perPeriod: 0.8, duration: 5, delay: 1, uncertainty: 0.3 },
      { target: 'manufacturing', immediate: 1, perPeriod: 0.4, duration: 4, delay: 2, uncertainty: 0.3 },
      { target: 'consumerConfidence', immediate: 2, perPeriod: 0.3, duration: 3, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'young_voters', impact: 6 },
      { groupId: 'urban_professionals', impact: 5 },
      { groupId: 'suburban_families', impact: 3 },
      { groupId: 'rural_regional', impact: -3 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'climate_gas_transition',
    name: 'Gas as Transitional Fuel Strategy',
    shortName: 'Gas Transition',
    description: 'Guarantee domestic gas reservation, fast-track new gas projects, and support gas as a firming fuel for intermittent renewables.',
    category: 'climate',
    stanceTable: {
      progressive: 'opposed',
      conservative: 'favoured',
      market: 'favoured',
      interventionist: 'neutral',
    },
    budgetCost: -3,
    economicEffects: [
      { target: 'energy', immediate: 3, perPeriod: 0.8, duration: 4, delay: 0, uncertainty: 0.3 },
      { target: 'businessConfidence', immediate: 3, perPeriod: 0.5, duration: 3, delay: 0, uncertainty: 0.2 },
      { target: 'manufacturing', immediate: 2, perPeriod: 0.4, duration: 4, delay: 1, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'business_owners', impact: 6 },
      { groupId: 'rural_regional', impact: 5 },
      { groupId: 'working_class', impact: 2 },
      { groupId: 'young_voters', impact: -6 },
      { groupId: 'urban_professionals', impact: -3 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'climate_carbon_tax',
    name: 'Carbon Price Mechanism',
    shortName: 'Carbon Tax',
    description: 'Introduce a $25/tonne carbon price rising to $50/tonne over five years, with revenue recycled as household energy rebates.',
    category: 'climate',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'opposed',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: 12,
    economicEffects: [
      { target: 'energy', immediate: -3, perPeriod: -0.5, duration: 5, delay: 0, uncertainty: 0.3 },
      { target: 'budgetBalance', immediate: 6, perPeriod: 2.0, duration: 5, delay: 0, uncertainty: 0.3 },
      { target: 'inflation', immediate: 1, perPeriod: 0.3, duration: 3, delay: 0, uncertainty: 0.2 },
      { target: 'businessConfidence', immediate: -4, perPeriod: -0.6, duration: 3, delay: 0, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'young_voters', impact: 6 },
      { groupId: 'urban_professionals', impact: 4 },
      { groupId: 'business_owners', impact: -8 },
      { groupId: 'rural_regional', impact: -6 },
      { groupId: 'working_class', impact: -3 },
    ],
    implementationRounds: 1,
    isLandmark: true,
  },

  {
    id: 'climate_reef',
    name: 'Great Barrier Reef and Environment Protection Fund',
    shortName: 'Reef Protection',
    description: 'Invest $1.2 billion in reef restoration, water quality improvement, and crown-of-thorns starfish control alongside strengthened environmental laws.',
    category: 'climate',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'neutral',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: -4,
    economicEffects: [
      { target: 'agriculture', immediate: 1, perPeriod: 0.4, duration: 4, delay: 1, uncertainty: 0.3 },
      { target: 'services', immediate: 2, perPeriod: 0.6, duration: 4, delay: 1, uncertainty: 0.3 },
      { target: 'consumerConfidence', immediate: 1, perPeriod: 0.3, duration: 3, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'young_voters', impact: 5 },
      { groupId: 'urban_professionals', impact: 4 },
      { groupId: 'rural_regional', impact: 3 },
      { groupId: 'suburban_families', impact: 2 },
    ],
    implementationRounds: 2,
    isLandmark: false,
  },

  // ============================================================
  // DEFENCE (7 policies)
  // ============================================================

  {
    id: 'defence_aukus',
    name: 'AUKUS Nuclear Submarine Program',
    shortName: 'AUKUS Subs',
    description: 'Proceed with the AUKUS trilateral agreement to acquire nuclear-powered submarines, building a new submarine construction yard in Adelaide.',
    category: 'defence',
    stanceTable: {
      progressive: 'neutral',
      conservative: 'favoured',
      market: 'favoured',
      interventionist: 'neutral',
    },
    budgetCost: -20,
    economicEffects: [
      { target: 'manufacturing', immediate: 5, perPeriod: 2.0, duration: 8, delay: 2, uncertainty: 0.4 },
      { target: 'technology', immediate: 3, perPeriod: 1.0, duration: 6, delay: 2, uncertainty: 0.3 },
      { target: 'unemployment', immediate: -1, perPeriod: -0.5, duration: 6, delay: 2, uncertainty: 0.3 },
      { target: 'budgetBalance', immediate: -10, perPeriod: -3.0, duration: 8, delay: 0, uncertainty: 0.3 },
      { target: 'publicDebt', immediate: 5, perPeriod: 1.5, duration: 8, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'business_owners', impact: 5 },
      { groupId: 'rural_regional', impact: 3 },
      { groupId: 'working_class', impact: 2 },
      { groupId: 'young_voters', impact: -4 },
      { groupId: 'public_sector', impact: -2 },
    ],
    implementationRounds: 3,
    isLandmark: true,
  },

  {
    id: 'defence_cyber',
    name: 'National Cyber Security Strategy',
    shortName: 'Cyber Security',
    description: 'Establish a national cyber security agency, mandate critical infrastructure protection standards, and fund cyber skills training.',
    category: 'defence',
    stanceTable: {
      progressive: 'neutral',
      conservative: 'favoured',
      market: 'favoured',
      interventionist: 'favoured',
    },
    budgetCost: -5,
    economicEffects: [
      { target: 'technology', immediate: 3, perPeriod: 1.0, duration: 5, delay: 1, uncertainty: 0.2 },
      { target: 'businessConfidence', immediate: 2, perPeriod: 0.5, duration: 4, delay: 1, uncertainty: 0.2 },
      { target: 'finance', immediate: 1, perPeriod: 0.3, duration: 4, delay: 1, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'urban_professionals', impact: 4 },
      { groupId: 'business_owners', impact: 5 },
      { groupId: 'suburban_families', impact: 2 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'defence_border',
    name: 'Enhanced Border Protection Operations',
    shortName: 'Border Protection',
    description: 'Increase Australian Border Force capabilities, expand maritime surveillance, and boost intelligence sharing with regional partners.',
    category: 'defence',
    stanceTable: {
      progressive: 'opposed',
      conservative: 'favoured',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: -6,
    economicEffects: [
      { target: 'services', immediate: 1, perPeriod: 0.3, duration: 4, delay: 0, uncertainty: 0.2 },
      { target: 'budgetBalance', immediate: -3, perPeriod: -0.8, duration: 4, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'rural_regional', impact: 6 },
      { groupId: 'suburban_families', impact: 4 },
      { groupId: 'retirees', impact: 3 },
      { groupId: 'young_voters', impact: -4 },
      { groupId: 'urban_professionals', impact: -3 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'defence_industry',
    name: 'Sovereign Defence Industry Investment',
    shortName: 'Defence Industry',
    description: 'Invest in guided weapons manufacturing, autonomous systems, and a domestic defence technology ecosystem in partnership with universities.',
    category: 'defence',
    stanceTable: {
      progressive: 'neutral',
      conservative: 'favoured',
      market: 'favoured',
      interventionist: 'favoured',
    },
    budgetCost: -8,
    economicEffects: [
      { target: 'manufacturing', immediate: 4, perPeriod: 1.2, duration: 6, delay: 2, uncertainty: 0.3 },
      { target: 'technology', immediate: 3, perPeriod: 0.8, duration: 5, delay: 1, uncertainty: 0.3 },
      { target: 'unemployment', immediate: -1, perPeriod: -0.3, duration: 5, delay: 2, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'business_owners', impact: 6 },
      { groupId: 'working_class', impact: 3 },
      { groupId: 'urban_professionals', impact: 3 },
      { groupId: 'young_voters', impact: -2 },
    ],
    implementationRounds: 2,
    isLandmark: false,
  },

  {
    id: 'defence_veterans',
    name: 'Veterans Affairs Royal Commission Response',
    shortName: 'Veterans Reform',
    description: 'Overhaul the DVA claims process, increase veterans\' mental health funding, and create a Veterans\' Wellbeing Commissioner.',
    category: 'defence',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'favoured',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: -4,
    economicEffects: [
      { target: 'healthcare', immediate: 2, perPeriod: 0.5, duration: 4, delay: 1, uncertainty: 0.2 },
      { target: 'consumerConfidence', immediate: 1, perPeriod: 0.3, duration: 3, delay: 0, uncertainty: 0.2 },
      { target: 'services', immediate: 1, perPeriod: 0.3, duration: 4, delay: 1, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'rural_regional', impact: 6 },
      { groupId: 'retirees', impact: 4 },
      { groupId: 'suburban_families', impact: 3 },
      { groupId: 'working_class', impact: 2 },
    ],
    implementationRounds: 2,
    isLandmark: false,
  },

  {
    id: 'defence_pacific',
    name: 'Pacific Security and Development Partnership',
    shortName: 'Pacific Partnership',
    description: 'Expand the Pacific Step-up with $2 billion in climate resilience, infrastructure, and security assistance for Pacific Island nations.',
    category: 'defence',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'favoured',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: -5,
    economicEffects: [
      { target: 'services', immediate: 1, perPeriod: 0.4, duration: 5, delay: 1, uncertainty: 0.3 },
      { target: 'businessConfidence', immediate: 1, perPeriod: 0.3, duration: 4, delay: 1, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'urban_professionals', impact: 3 },
      { groupId: 'rural_regional', impact: 2 },
      { groupId: 'young_voters', impact: 3 },
    ],
    implementationRounds: 2,
    isLandmark: false,
  },

  {
    id: 'defence_spending_gdp',
    name: 'Defence Spending to 2.5% of GDP',
    shortName: 'Defence 2.5% GDP',
    description: 'Commit to increasing defence spending to 2.5% of GDP over the forward estimates, funding equipment, personnel, and base upgrades.',
    category: 'defence',
    stanceTable: {
      progressive: 'opposed',
      conservative: 'favoured',
      market: 'neutral',
      interventionist: 'neutral',
    },
    budgetCost: -16,
    economicEffects: [
      { target: 'manufacturing', immediate: 3, perPeriod: 1.0, duration: 6, delay: 1, uncertainty: 0.3 },
      { target: 'unemployment', immediate: -1, perPeriod: -0.3, duration: 5, delay: 1, uncertainty: 0.2 },
      { target: 'budgetBalance', immediate: -8, perPeriod: -2.5, duration: 6, delay: 0, uncertainty: 0.2 },
      { target: 'publicDebt', immediate: 3, perPeriod: 1.0, duration: 6, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'rural_regional', impact: 5 },
      { groupId: 'retirees', impact: 3 },
      { groupId: 'business_owners', impact: 3 },
      { groupId: 'young_voters', impact: -5 },
      { groupId: 'public_sector', impact: -4 },
    ],
    implementationRounds: 2,
    isLandmark: true,
  },

  // ============================================================
  // INFRASTRUCTURE (7 policies)
  // ============================================================

  {
    id: 'infra_nbn_fibre',
    name: 'NBN Full Fibre-to-the-Premises Upgrade',
    shortName: 'NBN Fibre Upgrade',
    description: 'Complete the transition of the NBN to fibre-to-the-premises for 90% of premises, replacing copper and HFC connections.',
    category: 'infrastructure',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'neutral',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: -12,
    economicEffects: [
      { target: 'technology', immediate: 5, perPeriod: 1.5, duration: 6, delay: 2, uncertainty: 0.3 },
      { target: 'services', immediate: 2, perPeriod: 0.8, duration: 5, delay: 2, uncertainty: 0.3 },
      { target: 'gdpGrowth', immediate: 1, perPeriod: 0.6, duration: 5, delay: 2, uncertainty: 0.3 },
      { target: 'unemployment', immediate: -1, perPeriod: -0.3, duration: 4, delay: 1, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'urban_professionals', impact: 6 },
      { groupId: 'business_owners', impact: 5 },
      { groupId: 'suburban_families', impact: 5 },
      { groupId: 'rural_regional', impact: 4 },
      { groupId: 'young_voters', impact: 4 },
    ],
    implementationRounds: 3,
    isLandmark: true,
  },

  {
    id: 'infra_high_speed_rail',
    name: 'East Coast High-Speed Rail',
    shortName: 'High-Speed Rail',
    description: 'Commence construction of high-speed rail linking Melbourne, Canberra, Sydney, and Brisbane with regional stops, creating thousands of jobs.',
    category: 'infrastructure',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'neutral',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: -25,
    economicEffects: [
      { target: 'gdpGrowth', immediate: 3, perPeriod: 1.5, duration: 8, delay: 3, uncertainty: 0.4 },
      { target: 'unemployment', immediate: -2, perPeriod: -0.8, duration: 7, delay: 1, uncertainty: 0.3 },
      { target: 'manufacturing', immediate: 3, perPeriod: 1.0, duration: 6, delay: 1, uncertainty: 0.3 },
      { target: 'services', immediate: 1, perPeriod: 1.0, duration: 8, delay: 3, uncertainty: 0.4 },
      { target: 'publicDebt', immediate: 8, perPeriod: 2.0, duration: 8, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'working_class', impact: 6 },
      { groupId: 'rural_regional', impact: 7 },
      { groupId: 'urban_professionals', impact: 5 },
      { groupId: 'business_owners', impact: 3 },
      { groupId: 'young_voters', impact: 4 },
    ],
    implementationRounds: 3,
    isLandmark: true,
  },

  {
    id: 'infra_roads',
    name: 'National Road and Bridge Funding Package',
    shortName: 'Road Funding',
    description: 'Boost Roads to Recovery funding and invest in fixing congestion blackspots in major cities and sealing rural highways.',
    category: 'infrastructure',
    stanceTable: {
      progressive: 'neutral',
      conservative: 'favoured',
      market: 'favoured',
      interventionist: 'neutral',
    },
    budgetCost: -8,
    economicEffects: [
      { target: 'gdpGrowth', immediate: 2, perPeriod: 0.5, duration: 4, delay: 1, uncertainty: 0.2 },
      { target: 'unemployment', immediate: -1, perPeriod: -0.4, duration: 4, delay: 0, uncertainty: 0.2 },
      { target: 'services', immediate: 1, perPeriod: 0.4, duration: 4, delay: 1, uncertainty: 0.2 },
      { target: 'manufacturing', immediate: 1, perPeriod: 0.3, duration: 4, delay: 1, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'rural_regional', impact: 7 },
      { groupId: 'suburban_families', impact: 5 },
      { groupId: 'working_class', impact: 4 },
      { groupId: 'business_owners', impact: 4 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'infra_water',
    name: 'National Water Security Infrastructure',
    shortName: 'Water Infrastructure',
    description: 'Fund desalination upgrades, dam expansions, and water recycling plants to drought-proof major cities and agricultural regions.',
    category: 'infrastructure',
    stanceTable: {
      progressive: 'neutral',
      conservative: 'favoured',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: -7,
    economicEffects: [
      { target: 'agriculture', immediate: 3, perPeriod: 1.0, duration: 5, delay: 2, uncertainty: 0.3 },
      { target: 'services', immediate: 1, perPeriod: 0.3, duration: 4, delay: 2, uncertainty: 0.3 },
      { target: 'unemployment', immediate: -1, perPeriod: -0.3, duration: 4, delay: 1, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'rural_regional', impact: 8 },
      { groupId: 'suburban_families', impact: 3 },
      { groupId: 'working_class', impact: 3 },
      { groupId: 'business_owners', impact: 2 },
    ],
    implementationRounds: 3,
    isLandmark: false,
  },

  {
    id: 'infra_western_sydney',
    name: 'Western Sydney Airport and Aerotropolis',
    shortName: 'Western Sydney Airport',
    description: 'Fast-track completion of Nancy-Bird Walton Airport and develop the surrounding Aerotropolis precinct for advanced manufacturing and logistics.',
    category: 'infrastructure',
    stanceTable: {
      progressive: 'neutral',
      conservative: 'favoured',
      market: 'favoured',
      interventionist: 'neutral',
    },
    budgetCost: -10,
    economicEffects: [
      { target: 'services', immediate: 3, perPeriod: 1.0, duration: 6, delay: 2, uncertainty: 0.3 },
      { target: 'gdpGrowth', immediate: 2, perPeriod: 0.8, duration: 6, delay: 2, uncertainty: 0.3 },
      { target: 'unemployment', immediate: -2, perPeriod: -0.5, duration: 5, delay: 1, uncertainty: 0.3 },
      { target: 'manufacturing', immediate: 2, perPeriod: 0.6, duration: 5, delay: 2, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'working_class', impact: 5 },
      { groupId: 'business_owners', impact: 6 },
      { groupId: 'suburban_families', impact: 4 },
      { groupId: 'urban_professionals', impact: 2 },
    ],
    implementationRounds: 3,
    isLandmark: false,
  },

  {
    id: 'infra_ports',
    name: 'National Ports Modernisation Program',
    shortName: 'Ports Upgrade',
    description: 'Upgrade container handling capacity, automate operations, and improve road/rail connections at major ports to reduce supply chain bottlenecks.',
    category: 'infrastructure',
    stanceTable: {
      progressive: 'neutral',
      conservative: 'favoured',
      market: 'favoured',
      interventionist: 'neutral',
    },
    budgetCost: -6,
    economicEffects: [
      { target: 'services', immediate: 2, perPeriod: 0.6, duration: 5, delay: 2, uncertainty: 0.3 },
      { target: 'manufacturing', immediate: 2, perPeriod: 0.5, duration: 4, delay: 1, uncertainty: 0.3 },
      { target: 'gdpGrowth', immediate: 1, perPeriod: 0.4, duration: 5, delay: 2, uncertainty: 0.3 },
      { target: 'agriculture', immediate: 1, perPeriod: 0.3, duration: 4, delay: 2, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'business_owners', impact: 5 },
      { groupId: 'working_class', impact: 3 },
      { groupId: 'rural_regional', impact: 3 },
    ],
    implementationRounds: 2,
    isLandmark: false,
  },

  {
    id: 'infra_regional_rail',
    name: 'Regional Rail Revival Program',
    shortName: 'Regional Rail',
    description: 'Restore and upgrade regional rail lines connecting country towns to capital cities, with new rolling stock and improved frequency.',
    category: 'infrastructure',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'neutral',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: -7,
    economicEffects: [
      { target: 'services', immediate: 2, perPeriod: 0.6, duration: 5, delay: 2, uncertainty: 0.3 },
      { target: 'unemployment', immediate: -1, perPeriod: -0.3, duration: 4, delay: 1, uncertainty: 0.2 },
      { target: 'gdpGrowth', immediate: 1, perPeriod: 0.4, duration: 5, delay: 2, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'rural_regional', impact: 9 },
      { groupId: 'working_class', impact: 4 },
      { groupId: 'suburban_families', impact: 3 },
      { groupId: 'retirees', impact: 3 },
    ],
    implementationRounds: 2,
    isLandmark: false,
  },

  // ============================================================
  // WELFARE (7 policies)
  // ============================================================

  {
    id: 'welfare_jobseeker',
    name: 'JobSeeker Rate Increase to Poverty Line',
    shortName: 'Raise JobSeeker',
    description: 'Permanently increase the JobSeeker payment to at least $76 per day, aligning it with the Henderson poverty line.',
    category: 'welfare',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'opposed',
      market: 'opposed',
      interventionist: 'favoured',
    },
    budgetCost: -9,
    economicEffects: [
      { target: 'consumerConfidence', immediate: 3, perPeriod: 0.8, duration: 4, delay: 0, uncertainty: 0.2 },
      { target: 'gdpGrowth', immediate: 1, perPeriod: 0.3, duration: 4, delay: 0, uncertainty: 0.3 },
      { target: 'budgetBalance', immediate: -5, perPeriod: -1.5, duration: 5, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'working_class', impact: 7 },
      { groupId: 'young_voters', impact: 6 },
      { groupId: 'public_sector', impact: 4 },
      { groupId: 'business_owners', impact: -5 },
      { groupId: 'retirees', impact: -2 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'welfare_pension',
    name: 'Age Pension and Superannuation Reform',
    shortName: 'Pension Boost',
    description: 'Increase the Age Pension by $50 per fortnight, simplify the means test, and cap superannuation tax concessions for high balances.',
    category: 'welfare',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'neutral',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: -6,
    economicEffects: [
      { target: 'consumerConfidence', immediate: 3, perPeriod: 0.5, duration: 4, delay: 0, uncertainty: 0.2 },
      { target: 'budgetBalance', immediate: -4, perPeriod: -1.0, duration: 5, delay: 0, uncertainty: 0.2 },
      { target: 'finance', immediate: -1, perPeriod: -0.3, duration: 3, delay: 1, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'retirees', impact: 9 },
      { groupId: 'working_class', impact: 3 },
      { groupId: 'suburban_families', impact: 2 },
      { groupId: 'business_owners', impact: -3 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'welfare_parental_leave',
    name: 'Paid Parental Leave Extension to 26 Weeks',
    shortName: 'Parental Leave',
    description: 'Extend government-funded paid parental leave to 26 weeks at minimum wage with a use-it-or-lose-it partner component.',
    category: 'welfare',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'neutral',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: -5,
    economicEffects: [
      { target: 'consumerConfidence', immediate: 2, perPeriod: 0.5, duration: 4, delay: 0, uncertainty: 0.2 },
      { target: 'unemployment', immediate: 0, perPeriod: -0.2, duration: 4, delay: 1, uncertainty: 0.3 },
      { target: 'gdpGrowth', immediate: 0, perPeriod: 0.3, duration: 4, delay: 2, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'suburban_families', impact: 8 },
      { groupId: 'young_voters', impact: 7 },
      { groupId: 'working_class', impact: 5 },
      { groupId: 'urban_professionals', impact: 4 },
      { groupId: 'business_owners', impact: -3 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'welfare_disability',
    name: 'Disability Support Pension Access Reform',
    shortName: 'DSP Reform',
    description: 'Streamline Disability Support Pension access, reduce assessment wait times, and increase the payment for those with partial capacity to work.',
    category: 'welfare',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'neutral',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: -5,
    economicEffects: [
      { target: 'consumerConfidence', immediate: 2, perPeriod: 0.4, duration: 4, delay: 0, uncertainty: 0.2 },
      { target: 'healthcare', immediate: 1, perPeriod: 0.3, duration: 4, delay: 1, uncertainty: 0.2 },
      { target: 'budgetBalance', immediate: -3, perPeriod: -0.8, duration: 5, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'working_class', impact: 5 },
      { groupId: 'suburban_families', impact: 4 },
      { groupId: 'public_sector', impact: 4 },
      { groupId: 'young_voters', impact: 3 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'welfare_cost_of_living',
    name: 'Cost of Living Relief Package',
    shortName: 'Cost of Living',
    description: 'One-off energy bill relief, expanded Commonwealth Rent Assistance, cheaper medicines, and increased family tax benefit payments.',
    category: 'welfare',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'neutral',
      market: 'opposed',
      interventionist: 'favoured',
    },
    budgetCost: -8,
    economicEffects: [
      { target: 'consumerConfidence', immediate: 5, perPeriod: 0.5, duration: 3, delay: 0, uncertainty: 0.2 },
      { target: 'inflation', immediate: -1, perPeriod: -0.3, duration: 3, delay: 0, uncertainty: 0.3 },
      { target: 'budgetBalance', immediate: -5, perPeriod: -0.5, duration: 3, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'working_class', impact: 8 },
      { groupId: 'suburban_families', impact: 7 },
      { groupId: 'retirees', impact: 6 },
      { groupId: 'young_voters', impact: 5 },
      { groupId: 'business_owners', impact: -2 },
    ],
    implementationRounds: 0,
    isLandmark: false,
  },

  {
    id: 'welfare_rent_assistance',
    name: 'Commonwealth Rent Assistance Increase',
    shortName: 'Rent Assistance',
    description: 'Increase Commonwealth Rent Assistance by 40% and index it to actual rental price movements rather than CPI.',
    category: 'welfare',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'neutral',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: -4,
    economicEffects: [
      { target: 'consumerConfidence', immediate: 2, perPeriod: 0.5, duration: 4, delay: 0, uncertainty: 0.2 },
      { target: 'housing', immediate: 1, perPeriod: 0.3, duration: 4, delay: 0, uncertainty: 0.3 },
      { target: 'budgetBalance', immediate: -3, perPeriod: -0.6, duration: 4, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'working_class', impact: 6 },
      { groupId: 'young_voters', impact: 6 },
      { groupId: 'retirees', impact: 4 },
      { groupId: 'suburban_families', impact: 3 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'welfare_ubi_trial',
    name: 'Universal Basic Income Regional Trial',
    shortName: 'UBI Trial',
    description: 'Run a three-year UBI trial in selected disadvantaged regions, providing $500/week to all adult residents regardless of employment status.',
    category: 'welfare',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'opposed',
      market: 'opposed',
      interventionist: 'favoured',
    },
    budgetCost: -10,
    economicEffects: [
      { target: 'consumerConfidence', immediate: 3, perPeriod: 1.0, duration: 5, delay: 1, uncertainty: 0.4 },
      { target: 'gdpGrowth', immediate: 1, perPeriod: 0.5, duration: 5, delay: 1, uncertainty: 0.5 },
      { target: 'unemployment', immediate: 0, perPeriod: -0.3, duration: 5, delay: 2, uncertainty: 0.5 },
      { target: 'budgetBalance', immediate: -6, perPeriod: -1.5, duration: 5, delay: 0, uncertainty: 0.3 },
      { target: 'inflation', immediate: 1, perPeriod: 0.4, duration: 4, delay: 1, uncertainty: 0.4 },
    ],
    voterImpacts: [
      { groupId: 'young_voters', impact: 8 },
      { groupId: 'working_class', impact: 6 },
      { groupId: 'urban_professionals', impact: 3 },
      { groupId: 'business_owners', impact: -7 },
      { groupId: 'retirees', impact: -4 },
    ],
    implementationRounds: 2,
    isLandmark: true,
  },

  // ============================================================
  // IMMIGRATION (7 policies)
  // ============================================================

  {
    id: 'immig_skilled',
    name: 'Skilled Migration Program Expansion',
    shortName: 'Skilled Migration',
    description: 'Increase the permanent skilled migration intake to 200,000 with streamlined visa processing for critical shortage occupations.',
    category: 'immigration',
    stanceTable: {
      progressive: 'neutral',
      conservative: 'neutral',
      market: 'favoured',
      interventionist: 'neutral',
    },
    budgetCost: 2,
    economicEffects: [
      { target: 'gdpGrowth', immediate: 2, perPeriod: 0.8, duration: 5, delay: 1, uncertainty: 0.3 },
      { target: 'unemployment', immediate: 0, perPeriod: -0.4, duration: 4, delay: 1, uncertainty: 0.3 },
      { target: 'technology', immediate: 2, perPeriod: 0.5, duration: 4, delay: 1, uncertainty: 0.3 },
      { target: 'healthcare', immediate: 1, perPeriod: 0.3, duration: 4, delay: 1, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'business_owners', impact: 7 },
      { groupId: 'urban_professionals', impact: 3 },
      { groupId: 'working_class', impact: -3 },
      { groupId: 'rural_regional', impact: -2 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'immig_refugee',
    name: 'Humanitarian Refugee Intake Increase',
    shortName: 'Refugee Intake',
    description: 'Increase the humanitarian program to 30,000 places, improve settlement services, and create community sponsorship pathways.',
    category: 'immigration',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'opposed',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: -4,
    economicEffects: [
      { target: 'services', immediate: 1, perPeriod: 0.3, duration: 4, delay: 1, uncertainty: 0.3 },
      { target: 'gdpGrowth', immediate: 0, perPeriod: 0.3, duration: 5, delay: 2, uncertainty: 0.4 },
      { target: 'budgetBalance', immediate: -2, perPeriod: -0.5, duration: 4, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'young_voters', impact: 5 },
      { groupId: 'urban_professionals', impact: 4 },
      { groupId: 'rural_regional', impact: -5 },
      { groupId: 'retirees', impact: -3 },
      { groupId: 'suburban_families', impact: -2 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'immig_regional',
    name: 'Regional Migration Incentive Scheme',
    shortName: 'Regional Migration',
    description: 'Provide visa fast-tracking, relocation grants, and pathway to permanent residency for migrants who settle in regional areas for 3+ years.',
    category: 'immigration',
    stanceTable: {
      progressive: 'neutral',
      conservative: 'favoured',
      market: 'favoured',
      interventionist: 'neutral',
    },
    budgetCost: -3,
    economicEffects: [
      { target: 'gdpGrowth', immediate: 1, perPeriod: 0.4, duration: 4, delay: 1, uncertainty: 0.3 },
      { target: 'services', immediate: 1, perPeriod: 0.4, duration: 4, delay: 1, uncertainty: 0.3 },
      { target: 'agriculture', immediate: 1, perPeriod: 0.3, duration: 4, delay: 1, uncertainty: 0.2 },
      { target: 'unemployment', immediate: 0, perPeriod: -0.2, duration: 4, delay: 1, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'rural_regional', impact: 6 },
      { groupId: 'business_owners', impact: 5 },
      { groupId: 'working_class', impact: -2 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'immig_citizenship',
    name: 'Citizenship Pathway and Integration Reform',
    shortName: 'Citizenship Reform',
    description: 'Reduce citizenship wait times, lower English language requirements, expand settlement language programs, and recognise prior qualifications.',
    category: 'immigration',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'opposed',
      market: 'neutral',
      interventionist: 'neutral',
    },
    budgetCost: -2,
    economicEffects: [
      { target: 'services', immediate: 1, perPeriod: 0.3, duration: 4, delay: 1, uncertainty: 0.2 },
      { target: 'consumerConfidence', immediate: 1, perPeriod: 0.2, duration: 3, delay: 0, uncertainty: 0.2 },
      { target: 'unemployment', immediate: 0, perPeriod: -0.2, duration: 4, delay: 1, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'urban_professionals', impact: 4 },
      { groupId: 'young_voters', impact: 4 },
      { groupId: 'rural_regional', impact: -3 },
      { groupId: 'retirees', impact: -3 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'immig_temp_worker',
    name: 'Temporary Worker Exploitation Protection',
    shortName: 'Worker Protection',
    description: 'Crack down on wage theft of temporary visa holders, create a migrant worker ombudsman, and decouple visas from single employers.',
    category: 'immigration',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'neutral',
      market: 'neutral',
      interventionist: 'favoured',
    },
    budgetCost: -2,
    economicEffects: [
      { target: 'services', immediate: 1, perPeriod: 0.3, duration: 4, delay: 1, uncertainty: 0.2 },
      { target: 'consumerConfidence', immediate: 1, perPeriod: 0.2, duration: 3, delay: 0, uncertainty: 0.2 },
      { target: 'agriculture', immediate: -1, perPeriod: -0.3, duration: 3, delay: 0, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'working_class', impact: 5 },
      { groupId: 'young_voters', impact: 4 },
      { groupId: 'urban_professionals', impact: 3 },
      { groupId: 'business_owners', impact: -4 },
      { groupId: 'rural_regional', impact: -2 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'immig_student_visa',
    name: 'International Student Visa Reform',
    shortName: 'Student Visa Reform',
    description: 'Tighten student visa integrity measures, cap low-quality providers, and improve post-study work rights for graduates in priority fields.',
    category: 'immigration',
    stanceTable: {
      progressive: 'neutral',
      conservative: 'favoured',
      market: 'favoured',
      interventionist: 'neutral',
    },
    budgetCost: 1,
    economicEffects: [
      { target: 'education', immediate: 2, perPeriod: 0.5, duration: 4, delay: 1, uncertainty: 0.3 },
      { target: 'services', immediate: -1, perPeriod: 0.3, duration: 4, delay: 1, uncertainty: 0.3 },
      { target: 'technology', immediate: 1, perPeriod: 0.3, duration: 4, delay: 2, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'urban_professionals', impact: 3 },
      { groupId: 'business_owners', impact: 2 },
      { groupId: 'young_voters', impact: 2 },
      { groupId: 'suburban_families', impact: 2 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'immig_pacific_labour',
    name: 'Pacific Labour Mobility Expansion',
    shortName: 'Pacific Workers',
    description: 'Expand the Pacific Australia Labour Mobility scheme with better worker protections, pastoral care, and a pathway to permanent residency.',
    category: 'immigration',
    stanceTable: {
      progressive: 'favoured',
      conservative: 'neutral',
      market: 'favoured',
      interventionist: 'neutral',
    },
    budgetCost: -2,
    economicEffects: [
      { target: 'agriculture', immediate: 2, perPeriod: 0.6, duration: 4, delay: 0, uncertainty: 0.2 },
      { target: 'services', immediate: 1, perPeriod: 0.3, duration: 4, delay: 0, uncertainty: 0.2 },
      { target: 'unemployment', immediate: 0, perPeriod: -0.2, duration: 4, delay: 0, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'rural_regional', impact: 5 },
      { groupId: 'business_owners', impact: 4 },
      { groupId: 'working_class', impact: -2 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  // ============================================================
  // TRADE (7 policies)
  // ============================================================

  {
    id: 'trade_eu_fta',
    name: 'Australia-EU Free Trade Agreement',
    shortName: 'AU-EU FTA',
    description: 'Finalise a comprehensive free trade agreement with the European Union, covering goods, services, investment, and geographic indications.',
    category: 'trade',
    stanceTable: {
      progressive: 'neutral',
      conservative: 'favoured',
      market: 'favoured',
      interventionist: 'opposed',
    },
    budgetCost: 3,
    economicEffects: [
      { target: 'gdpGrowth', immediate: 2, perPeriod: 0.8, duration: 6, delay: 2, uncertainty: 0.3 },
      { target: 'agriculture', immediate: 3, perPeriod: 1.0, duration: 5, delay: 2, uncertainty: 0.3 },
      { target: 'services', immediate: 2, perPeriod: 0.6, duration: 5, delay: 2, uncertainty: 0.3 },
      { target: 'businessConfidence', immediate: 3, perPeriod: 0.5, duration: 4, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'business_owners', impact: 7 },
      { groupId: 'rural_regional', impact: 5 },
      { groupId: 'urban_professionals', impact: 3 },
      { groupId: 'working_class', impact: -2 },
    ],
    implementationRounds: 2,
    isLandmark: true,
  },

  {
    id: 'trade_tariff_reform',
    name: 'Tariff Reform and Simplification',
    shortName: 'Tariff Reform',
    description: 'Eliminate nuisance tariffs on 3,000+ product categories and simplify customs processes to reduce import costs for businesses.',
    category: 'trade',
    stanceTable: {
      progressive: 'neutral',
      conservative: 'neutral',
      market: 'favoured',
      interventionist: 'opposed',
    },
    budgetCost: -2,
    economicEffects: [
      { target: 'inflation', immediate: -1, perPeriod: -0.3, duration: 4, delay: 1, uncertainty: 0.2 },
      { target: 'businessConfidence', immediate: 2, perPeriod: 0.5, duration: 4, delay: 0, uncertainty: 0.2 },
      { target: 'services', immediate: 1, perPeriod: 0.3, duration: 4, delay: 1, uncertainty: 0.2 },
      { target: 'budgetBalance', immediate: -2, perPeriod: -0.3, duration: 4, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'business_owners', impact: 5 },
      { groupId: 'urban_professionals', impact: 2 },
      { groupId: 'working_class', impact: -2 },
      { groupId: 'manufacturing', impact: -3 },
    ],
    implementationRounds: 1,
    isLandmark: false,
  },

  {
    id: 'trade_export_diversify',
    name: 'Export Market Diversification Strategy',
    shortName: 'Export Diversity',
    description: 'Reduce trade dependence on any single market by funding Austrade offices in India, Southeast Asia, and Africa with export finance support.',
    category: 'trade',
    stanceTable: {
      progressive: 'neutral',
      conservative: 'favoured',
      market: 'favoured',
      interventionist: 'favoured',
    },
    budgetCost: -4,
    economicEffects: [
      { target: 'gdpGrowth', immediate: 1, perPeriod: 0.5, duration: 5, delay: 2, uncertainty: 0.4 },
      { target: 'agriculture', immediate: 2, perPeriod: 0.6, duration: 5, delay: 2, uncertainty: 0.3 },
      { target: 'services', immediate: 1, perPeriod: 0.4, duration: 5, delay: 2, uncertainty: 0.3 },
      { target: 'businessConfidence', immediate: 2, perPeriod: 0.4, duration: 4, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'business_owners', impact: 6 },
      { groupId: 'rural_regional', impact: 5 },
      { groupId: 'urban_professionals', impact: 2 },
    ],
    implementationRounds: 2,
    isLandmark: false,
  },

  {
    id: 'trade_manufacturing_fund',
    name: 'National Manufacturing Sovereignty Fund',
    shortName: 'Made in Australia',
    description: 'Establish a $15 billion fund to rebuild sovereign manufacturing capability in critical sectors: medical supplies, semiconductors, and defence.',
    category: 'trade',
    stanceTable: {
      progressive: 'neutral',
      conservative: 'neutral',
      market: 'opposed',
      interventionist: 'favoured',
    },
    budgetCost: -15,
    economicEffects: [
      { target: 'manufacturing', immediate: 6, perPeriod: 2.0, duration: 7, delay: 2, uncertainty: 0.4 },
      { target: 'unemployment', immediate: -2, perPeriod: -0.6, duration: 6, delay: 2, uncertainty: 0.3 },
      { target: 'gdpGrowth', immediate: 1, perPeriod: 0.8, duration: 6, delay: 2, uncertainty: 0.4 },
      { target: 'technology', immediate: 3, perPeriod: 1.0, duration: 6, delay: 2, uncertainty: 0.3 },
      { target: 'publicDebt', immediate: 4, perPeriod: 1.0, duration: 6, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'working_class', impact: 7 },
      { groupId: 'business_owners', impact: 4 },
      { groupId: 'rural_regional', impact: 4 },
      { groupId: 'urban_professionals', impact: 2 },
    ],
    implementationRounds: 3,
    isLandmark: true,
  },

  {
    id: 'trade_agriculture_export',
    name: 'Agricultural Export Enhancement Program',
    shortName: 'Ag Export Boost',
    description: 'Fund biosecurity upgrades, cold chain infrastructure, and trade missions to open premium markets for Australian agricultural exports.',
    category: 'trade',
    stanceTable: {
      progressive: 'neutral',
      conservative: 'favoured',
      market: 'favoured',
      interventionist: 'neutral',
    },
    budgetCost: -5,
    economicEffects: [
      { target: 'agriculture', immediate: 4, perPeriod: 1.2, duration: 5, delay: 1, uncertainty: 0.3 },
      { target: 'gdpGrowth', immediate: 1, perPeriod: 0.4, duration: 4, delay: 1, uncertainty: 0.3 },
      { target: 'services', immediate: 1, perPeriod: 0.3, duration: 4, delay: 1, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'rural_regional', impact: 8 },
      { groupId: 'business_owners', impact: 5 },
      { groupId: 'working_class', impact: 2 },
    ],
    implementationRounds: 2,
    isLandmark: false,
  },

  {
    id: 'trade_digital_framework',
    name: 'Digital Trade and E-Commerce Framework',
    shortName: 'Digital Trade',
    description: 'Establish rules for cross-border data flows, digital services taxes, and consumer protection in international e-commerce.',
    category: 'trade',
    stanceTable: {
      progressive: 'neutral',
      conservative: 'neutral',
      market: 'favoured',
      interventionist: 'neutral',
    },
    budgetCost: -1,
    economicEffects: [
      { target: 'technology', immediate: 3, perPeriod: 0.8, duration: 5, delay: 1, uncertainty: 0.3 },
      { target: 'services', immediate: 2, perPeriod: 0.5, duration: 4, delay: 1, uncertainty: 0.3 },
      { target: 'businessConfidence', immediate: 2, perPeriod: 0.4, duration: 4, delay: 0, uncertainty: 0.2 },
    ],
    voterImpacts: [
      { groupId: 'urban_professionals', impact: 5 },
      { groupId: 'business_owners', impact: 5 },
      { groupId: 'young_voters', impact: 3 },
    ],
    implementationRounds: 2,
    isLandmark: false,
  },

  {
    id: 'trade_critical_minerals',
    name: 'Critical Minerals Export and Processing Strategy',
    shortName: 'Critical Minerals',
    description: 'Fast-track approvals for lithium, cobalt, and rare earth projects with value-adding processing requirements and offtake agreements with allies.',
    category: 'trade',
    stanceTable: {
      progressive: 'neutral',
      conservative: 'favoured',
      market: 'favoured',
      interventionist: 'favoured',
    },
    budgetCost: -6,
    economicEffects: [
      { target: 'manufacturing', immediate: 3, perPeriod: 1.2, duration: 6, delay: 2, uncertainty: 0.4 },
      { target: 'energy', immediate: 2, perPeriod: 0.8, duration: 6, delay: 2, uncertainty: 0.3 },
      { target: 'gdpGrowth', immediate: 1, perPeriod: 0.6, duration: 6, delay: 2, uncertainty: 0.4 },
      { target: 'unemployment', immediate: -1, perPeriod: -0.4, duration: 5, delay: 1, uncertainty: 0.3 },
    ],
    voterImpacts: [
      { groupId: 'rural_regional', impact: 7 },
      { groupId: 'business_owners', impact: 6 },
      { groupId: 'working_class', impact: 4 },
      { groupId: 'young_voters', impact: 2 },
    ],
    implementationRounds: 2,
    isLandmark: false,
  },

];

/**
 * Returns a deep copy of the full policy list.
 * Prevents mutation of the master definitions during gameplay.
 */
export function getAllPolicies(): Policy[] {
  return POLICIES.map(p => ({
    ...p,
    stanceTable: { ...p.stanceTable },
    economicEffects: p.economicEffects.map(e => ({ ...e })),
    voterImpacts: p.voterImpacts.map(v => ({ ...v })),
  }));
}
