import { PolicySlider, PolicyCategory, PolicyEffect, LinkFormula } from '../types';

// ============================================================
// POLICY DEFINITIONS — The core of the simulation web
// 45 policies across 9 categories, tuned for Australian politics
//
// Each policy is a slider (0-1) with interconnected effects on
// stats, voter groups, and situations. The web of effects creates
// emergent gameplay where every decision has trade-offs.
//
// Default values reflect approximate real Australian policy
// settings circa 2024. costPerPoint is billions AUD at full level.
// ============================================================

function policy(
  id: string,
  name: string,
  shortName: string,
  description: string,
  category: PolicyCategory,
  icon: string,
  minLabel: string,
  maxLabel: string,
  defaultValue: number,
  costPerPoint: number,
  implementationDelay: number,
  effects: PolicyEffect[],
  ideologicalBias: { social: number; economic: number },
): PolicySlider {
  return {
    id,
    name,
    shortName,
    description,
    category,
    icon,
    minLabel,
    maxLabel,
    currentValue: defaultValue,
    targetValue: defaultValue,
    defaultValue,
    costPerPoint,
    implementationDelay,
    effects,
    ideologicalBias,
  };
}

function effect(
  targetId: string,
  multiplier: number,
  formula: LinkFormula = 'linear',
  delay: number = 0,
  inertia: number = 0.2,
): PolicyEffect {
  return { targetId, multiplier, formula, delay, inertia };
}

export function getAllPolicies(): PolicySlider[] {
  return [

    // ================================================================
    // TAX POLICIES (7)
    // Revenue generation with economic and social trade-offs.
    // Higher taxes fund services but can dampen growth and upset
    // business-aligned voters.
    // ================================================================

    policy(
      'income_tax',
      'Income Tax',
      'Income Tax',
      'Personal income tax levied on wages and salaries through progressive brackets. Higher rates fund public services but reduce disposable income and can dampen economic activity. Australia\'s top marginal rate is 45% above $180k.',
      'tax',
      '\u{1F4B0}',
      'None',
      'Maximum',
      0.55,
      180,
      2,
      [
        effect('gdp_growth', -0.25, 'squared', 1, 0.3),
        effect('equality', 0.35, 'sqrt', 0, 0.2),
        effect('public_debt', -0.40, 'linear', 0, 0.1),
        effect('poverty_rate', -0.15, 'sqrt', 1, 0.3),
        effect('consumer_confidence', -0.12, 'linear', 0, 0.2),
        effect('wealthy', -0.50, 'squared', 0, 0.1),
        effect('workers', -0.20, 'linear', 0, 0.2),
        effect('business_owners', -0.25, 'linear', 0, 0.2),
      ],
      { social: 0.3, economic: 0.7 },
    ),

    policy(
      'corporate_tax',
      'Corporate Tax',
      'Corp Tax',
      'Tax on company profits currently at 30% (25% for small business). Funds public expenditure but may discourage investment and push businesses offshore if set too high relative to regional competitors.',
      'tax',
      '\u{1F3E2}',
      'None',
      'Maximum',
      0.45,
      160,
      2,
      [
        effect('gdp_growth', -0.30, 'squared', 1, 0.3),
        effect('public_debt', -0.35, 'linear', 0, 0.1),
        effect('unemployment', 0.15, 'threshold', 2, 0.4),
        effect('business_owners', -0.60, 'linear', 0, 0.1),
        effect('workers', 0.10, 'sqrt', 1, 0.3),
        effect('tech_workers', -0.10, 'linear', 1, 0.3),
        effect('brain_drain', 0.15, 'threshold', 3, 0.5),
      ],
      { social: 0.1, economic: 0.8 },
    ),

    policy(
      'gst',
      'Goods & Services Tax',
      'GST',
      'A broad-based 10% consumption tax on most goods and services. Regressive in nature but provides stable revenue. Exemptions exist for fresh food, health services, and education.',
      'tax',
      '\u{1F6D2}',
      'None',
      '20%',
      0.35,
      120,
      1,
      [
        effect('public_debt', -0.30, 'linear', 0, 0.1),
        effect('consumer_confidence', -0.20, 'linear', 0, 0.2),
        effect('equality', -0.20, 'sqrt', 0, 0.2),
        effect('inflation', 0.10, 'linear', 0, 0.2),
        effect('workers', -0.25, 'linear', 0, 0.2),
        effect('retirees', -0.30, 'linear', 0, 0.1),
        effect('poverty_rate', 0.10, 'sqrt', 1, 0.3),
      ],
      { social: -0.2, economic: -0.3 },
    ),

    policy(
      'capital_gains_tax',
      'Capital Gains Tax',
      'CGT',
      'Tax on profits from selling assets such as property and shares. Australia offers a 50% discount for assets held over 12 months. Affects investment behaviour and wealth distribution significantly.',
      'tax',
      '\u{1F4C8}',
      'None',
      'Maximum',
      0.45,
      80,
      2,
      [
        effect('equality', 0.25, 'sqrt', 1, 0.3),
        effect('public_debt', -0.15, 'linear', 0, 0.1),
        effect('housing_affordability', 0.20, 'sqrt', 2, 0.4),
        effect('gdp_growth', -0.08, 'linear', 1, 0.3),
        effect('wealthy', -0.55, 'linear', 0, 0.1),
        effect('business_owners', -0.20, 'linear', 0, 0.2),
        effect('housing_crisis', -0.15, 'sqrt', 2, 0.5),
      ],
      { social: 0.2, economic: 0.5 },
    ),

    policy(
      'mining_royalties',
      'Mining Royalties',
      'Mining Tax',
      'Royalties and super-profits taxes on mining companies extracting Australian minerals and resources. A political flashpoint given the immense power of the mining lobby and the "minerals belong to the people" argument.',
      'tax',
      '\u{26CF}\u{FE0F}',
      'Minimal',
      'Maximum',
      0.40,
      90,
      2,
      [
        effect('public_debt', -0.20, 'linear', 0, 0.1),
        effect('gdp_growth', -0.10, 'threshold', 1, 0.3),
        effect('environment_quality', 0.10, 'sqrt', 1, 0.3),
        effect('business_owners', -0.35, 'linear', 0, 0.1),
        effect('workers', 0.10, 'sqrt', 1, 0.3),
        effect('environmentalists', 0.25, 'sqrt', 0, 0.2),
        effect('mining_boom', -0.20, 'threshold', 1, 0.4),
      ],
      { social: 0.2, economic: 0.5 },
    ),

    policy(
      'carbon_tax',
      'Carbon Pricing',
      'Carbon Tax',
      'A price on carbon emissions to incentivise greenhouse gas reductions. Was introduced by Gillard in 2012 then repealed by Abbott in 2014. Remains one of the most politically toxic and divisive issues in Australian politics.',
      'tax',
      '\u{1F32B}\u{FE0F}',
      'None',
      'High Price',
      0.15,
      70,
      3,
      [
        effect('environment_quality', 0.40, 'sqrt', 2, 0.4),
        effect('gdp_growth', -0.10, 'linear', 1, 0.3),
        effect('consumer_confidence', -0.10, 'linear', 0, 0.2),
        effect('inflation', 0.06, 'linear', 0, 0.2),
        effect('environmentalists', 0.60, 'linear', 0, 0.1),
        effect('business_owners', -0.30, 'linear', 0, 0.2),
        effect('motorists', -0.25, 'linear', 0, 0.2),
        effect('climate_emergency', -0.30, 'sqrt', 3, 0.5),
        effect('green_transition', 0.35, 'sqrt', 2, 0.4),
      ],
      { social: 0.6, economic: 0.4 },
    ),

    policy(
      'luxury_tax',
      'Luxury Goods Tax',
      'Luxury Tax',
      'Additional tax on high-end goods including luxury cars, yachts, fine jewellery, and premium spirits. Modest in revenue terms but symbolically important for egalitarian politics.',
      'tax',
      '\u{1F48E}',
      'None',
      'Heavy',
      0.30,
      25,
      1,
      [
        effect('public_debt', -0.08, 'linear', 0, 0.1),
        effect('equality', 0.10, 'sqrt', 0, 0.2),
        effect('consumer_confidence', -0.05, 'linear', 0, 0.2),
        effect('wealthy', -0.40, 'linear', 0, 0.1),
        effect('workers', 0.10, 'sqrt', 0, 0.2),
      ],
      { social: 0.3, economic: 0.5 },
    ),

    // ================================================================
    // ECONOMY POLICIES (6)
    // Direct intervention in the economy: wages, subsidies, trade.
    // Balance growth against equality, business against workers.
    // ================================================================

    policy(
      'minimum_wage',
      'Minimum Wage',
      'Min Wage',
      'The national minimum wage set annually by the Fair Work Commission. Australia has one of the highest minimum wages in the world. A defining feature of the industrial relations system.',
      'economy',
      '\u{1F4B5}',
      'Abolished',
      'Very High',
      0.65,
      0,
      2,
      [
        effect('equality', 0.30, 'sqrt', 1, 0.3),
        effect('poverty_rate', -0.25, 'sqrt', 1, 0.3),
        effect('unemployment', 0.15, 'squared', 2, 0.4),
        effect('consumer_confidence', 0.15, 'linear', 1, 0.2),
        effect('inflation', 0.08, 'linear', 1, 0.3),
        effect('workers', 0.50, 'linear', 0, 0.1),
        effect('business_owners', -0.35, 'linear', 0, 0.2),
        effect('students', 0.15, 'sqrt', 0, 0.2),
      ],
      { social: 0.3, economic: 0.7 },
    ),

    policy(
      'business_subsidies',
      'Business Subsidies',
      'Biz Subs',
      'Direct subsidies, tax concessions, and investment incentives for large businesses to encourage job creation, capital investment, and economic growth.',
      'economy',
      '\u{1F3ED}',
      'None',
      'Generous',
      0.40,
      60,
      2,
      [
        effect('gdp_growth', 0.20, 'sqrt', 1, 0.3),
        effect('unemployment', -0.15, 'sqrt', 2, 0.4),
        effect('public_debt', 0.15, 'linear', 0, 0.1),
        effect('equality', -0.15, 'linear', 1, 0.3),
        effect('business_owners', 0.50, 'linear', 0, 0.1),
        effect('workers', 0.10, 'sqrt', 2, 0.4),
        effect('economic_boom', 0.10, 'threshold', 3, 0.5),
      ],
      { social: -0.2, economic: -0.6 },
    ),

    policy(
      'rnd_funding',
      'R&D Tax Incentives',
      'R&D Fund',
      'Government incentives and tax offsets for research and development spending. Crucial for diversifying Australia beyond resource extraction and agriculture toward a knowledge economy.',
      'economy',
      '\u{1F52C}',
      'None',
      'Maximum',
      0.45,
      50,
      3,
      [
        effect('technology_level', 0.40, 'sqrt', 2, 0.4),
        effect('gdp_growth', 0.15, 'sqrt', 3, 0.5),
        effect('public_debt', 0.10, 'linear', 0, 0.1),
        effect('tech_workers', 0.40, 'sqrt', 1, 0.3),
        effect('business_owners', 0.20, 'sqrt', 1, 0.3),
        effect('brain_drain', -0.25, 'sqrt', 2, 0.4),
        effect('tech_boom', 0.25, 'threshold', 3, 0.5),
      ],
      { social: 0.1, economic: 0.0 },
    ),

    policy(
      'trade_tariffs',
      'Trade Tariffs',
      'Tariffs',
      'Import tariffs and trade barriers. Australia has broadly embraced free trade with numerous FTAs (China, Japan, US, UK, ASEAN), but some protectionism remains for sensitive sectors.',
      'economy',
      '\u{1F6A2}',
      'Free Trade',
      'Protectionist',
      0.20,
      15,
      2,
      [
        effect('gdp_growth', -0.15, 'linear', 1, 0.3),
        effect('international_relations', -0.25, 'linear', 1, 0.2),
        effect('unemployment', -0.10, 'sqrt', 2, 0.4),
        effect('consumer_confidence', -0.10, 'linear', 0, 0.2),
        effect('farmers', 0.15, 'sqrt', 1, 0.3),
        effect('workers', 0.15, 'sqrt', 1, 0.3),
        effect('business_owners', -0.15, 'linear', 0, 0.3),
      ],
      { social: -0.1, economic: 0.3 },
    ),

    policy(
      'small_business_grants',
      'Small Business Grants',
      'SME Grants',
      'Grants, low-interest loans, and mentoring programs specifically for small and medium enterprises. SMEs employ the majority of Australians and are the backbone of regional economies.',
      'economy',
      '\u{1F3EA}',
      'None',
      'Generous',
      0.35,
      30,
      1,
      [
        effect('gdp_growth', 0.10, 'sqrt', 1, 0.3),
        effect('unemployment', -0.10, 'sqrt', 2, 0.4),
        effect('public_debt', 0.08, 'linear', 0, 0.1),
        effect('business_owners', 0.40, 'linear', 0, 0.1),
        effect('workers', 0.10, 'sqrt', 1, 0.3),
        effect('consumer_confidence', 0.10, 'sqrt', 1, 0.2),
      ],
      { social: 0.0, economic: -0.2 },
    ),

    policy(
      'agricultural_subsidies',
      'Agricultural Subsidies',
      'Farm Subs',
      'Support payments, drought relief, and water management subsidies for Australian farmers. Includes crop insurance programs and the Farm Household Allowance for those in hardship.',
      'economy',
      '\u{1F33E}',
      'None',
      'Generous',
      0.35,
      35,
      1,
      [
        effect('public_debt', 0.08, 'linear', 0, 0.1),
        effect('farmers', 0.55, 'linear', 0, 0.1),
        effect('environment_quality', -0.10, 'linear', 1, 0.3),
        effect('drought', -0.15, 'sqrt', 1, 0.4),
        effect('indigenous', 0.05, 'sqrt', 1, 0.3),
        effect('consumer_confidence', 0.05, 'linear', 1, 0.2),
      ],
      { social: -0.1, economic: 0.2 },
    ),

    // ================================================================
    // WELFARE POLICIES (6)
    // The social safety net. High welfare reduces poverty and
    // pleases vulnerable groups but costs money and can create
    // dependency narratives in conservative media.
    // ================================================================

    policy(
      'unemployment_benefits',
      'JobSeeker Payments',
      'JobSeeker',
      'Unemployment benefits for those actively seeking work. Politically contentious: too low causes hardship and homelessness, too high may reduce incentive to work according to critics.',
      'welfare',
      '\u{1F4CB}',
      'None',
      'Generous',
      0.40,
      45,
      1,
      [
        effect('poverty_rate', -0.30, 'sqrt', 0, 0.2),
        effect('unemployment', 0.08, 'threshold', 1, 0.4),
        effect('equality', 0.20, 'sqrt', 0, 0.2),
        effect('public_debt', 0.12, 'linear', 0, 0.1),
        effect('consumer_confidence', 0.10, 'sqrt', 0, 0.2),
        effect('workers', 0.15, 'sqrt', 0, 0.2),
        effect('homelessness', -0.20, 'sqrt', 0, 0.3),
        effect('crime_rate', -0.05, 'sqrt', 1, 0.3),
      ],
      { social: 0.4, economic: 0.6 },
    ),

    policy(
      'aged_pension',
      'Aged Pension',
      'Pension',
      'Government pension for retirees who meet age and means-testing requirements. A massive and growing part of the federal budget as Australia\'s population ages. The Age Pension age is 67.',
      'welfare',
      '\u{1F9D3}',
      'None',
      'Generous',
      0.55,
      80,
      1,
      [
        effect('poverty_rate', -0.20, 'sqrt', 0, 0.2),
        effect('public_debt', 0.18, 'linear', 0, 0.1),
        effect('equality', 0.15, 'sqrt', 0, 0.2),
        effect('consumer_confidence', 0.10, 'sqrt', 0, 0.2),
        effect('retirees', 0.65, 'linear', 0, 0.1),
        effect('aging_population', -0.10, 'sqrt', 0, 0.3),
      ],
      { social: 0.2, economic: 0.4 },
    ),

    policy(
      'disability_support',
      'NDIS & Disability Support',
      'NDIS',
      'The National Disability Insurance Scheme provides individualised funding for Australians with significant and permanent disabilities. One of the largest social programs ever created in Australia, now costing over $35 billion annually.',
      'welfare',
      '\u{267F}',
      'Minimal',
      'Comprehensive',
      0.55,
      85,
      2,
      [
        effect('equality', 0.25, 'sqrt', 1, 0.3),
        effect('public_debt', 0.20, 'linear', 0, 0.1),
        effect('health_quality', 0.10, 'sqrt', 1, 0.3),
        effect('poverty_rate', -0.10, 'sqrt', 1, 0.3),
        effect('healthcare_workers', 0.30, 'sqrt', 0, 0.2),
        effect('parents', 0.20, 'sqrt', 0, 0.2),
      ],
      { social: 0.5, economic: 0.5 },
    ),

    policy(
      'childcare_subsidies',
      'Childcare Subsidies',
      'Childcare',
      'Government subsidies to reduce the cost of childcare, enabling workforce participation particularly for women. A key driver of gender equality and labour supply, with the Child Care Subsidy covering up to 90% of fees.',
      'welfare',
      '\u{1F476}',
      'None',
      'Free Childcare',
      0.45,
      40,
      1,
      [
        effect('unemployment', -0.08, 'sqrt', 1, 0.3),
        effect('gdp_growth', 0.08, 'sqrt', 2, 0.4),
        effect('equality', 0.15, 'sqrt', 1, 0.3),
        effect('public_debt', 0.10, 'linear', 0, 0.1),
        effect('parents', 0.55, 'linear', 0, 0.1),
        effect('workers', 0.15, 'sqrt', 0, 0.2),
        effect('poverty_rate', -0.08, 'sqrt', 1, 0.3),
      ],
      { social: 0.4, economic: 0.3 },
    ),

    policy(
      'housing_assistance',
      'Housing Assistance',
      'Housing Aid',
      'Public housing construction, Commonwealth Rent Assistance, and first home buyer schemes. Critical as Australia faces a deepening housing affordability crisis in major cities.',
      'welfare',
      '\u{1F3E0}',
      'None',
      'Comprehensive',
      0.35,
      55,
      2,
      [
        effect('housing_affordability', 0.30, 'sqrt', 2, 0.4),
        effect('homelessness', -0.35, 'sqrt', 1, 0.3),
        effect('public_debt', 0.12, 'linear', 0, 0.1),
        effect('poverty_rate', -0.15, 'sqrt', 1, 0.3),
        effect('housing_crisis', -0.25, 'sqrt', 2, 0.5),
        effect('workers', 0.15, 'sqrt', 1, 0.3),
        effect('immigrants', 0.15, 'sqrt', 1, 0.3),
        effect('students', 0.10, 'sqrt', 1, 0.3),
      ],
      { social: 0.4, economic: 0.5 },
    ),

    policy(
      'family_tax_benefit',
      'Family Tax Benefit',
      'Family Ben',
      'Means-tested payments to assist families with the cost of raising children. Includes FTB Part A (per child, income tested) and FTB Part B (additional payment for single-income families).',
      'welfare',
      '\u{1F46A}',
      'None',
      'Generous',
      0.45,
      50,
      1,
      [
        effect('poverty_rate', -0.15, 'sqrt', 0, 0.2),
        effect('public_debt', 0.10, 'linear', 0, 0.1),
        effect('equality', 0.10, 'sqrt', 0, 0.2),
        effect('consumer_confidence', 0.10, 'sqrt', 0, 0.2),
        effect('parents', 0.50, 'linear', 0, 0.1),
        effect('retirees', 0.05, 'sqrt', 0, 0.3),
        effect('religious', 0.15, 'sqrt', 0, 0.2),
      ],
      { social: 0.1, economic: 0.4 },
    ),

    // ================================================================
    // HEALTH POLICIES (4)
    // Australia's healthcare system is a mix of public (Medicare)
    // and private. Health funding is expensive but essential, and
    // healthcare workers are a significant voter bloc.
    // ================================================================

    policy(
      'medicare_funding',
      'Medicare Funding',
      'Medicare',
      'Funding for Australia\'s universal public healthcare system, the crown jewel of the welfare state. Provides free or subsidised GP visits, specialist referrals, and public hospital care. Partly funded by the 2% Medicare levy.',
      'health',
      '\u{1FA7A}',
      'Defunded',
      'Comprehensive',
      0.65,
      100,
      2,
      [
        effect('health_quality', 0.45, 'sqrt', 1, 0.3),
        effect('public_debt', 0.22, 'linear', 0, 0.1),
        effect('poverty_rate', -0.10, 'sqrt', 1, 0.3),
        effect('healthcare_crisis', -0.35, 'sqrt', 1, 0.4),
        effect('healthcare_workers', 0.45, 'linear', 0, 0.1),
        effect('workers', 0.20, 'sqrt', 0, 0.2),
        effect('retirees', 0.30, 'sqrt', 0, 0.2),
        effect('obesity_epidemic', -0.10, 'sqrt', 2, 0.5),
      ],
      { social: 0.5, economic: 0.5 },
    ),

    policy(
      'mental_health_funding',
      'Mental Health Funding',
      'Mental Health',
      'Dedicated funding for mental health services, counselling, crisis support lines, and community care. An increasingly urgent area as rates of anxiety, depression, and youth self-harm rise across Australia.',
      'health',
      '\u{1F9E0}',
      'Minimal',
      'Comprehensive',
      0.35,
      30,
      2,
      [
        effect('health_quality', 0.15, 'sqrt', 1, 0.3),
        effect('crime_rate', -0.08, 'sqrt', 2, 0.4),
        effect('public_debt', 0.07, 'linear', 0, 0.1),
        effect('mental_health_crisis', -0.40, 'sqrt', 2, 0.4),
        effect('students', 0.25, 'sqrt', 0, 0.2),
        effect('healthcare_workers', 0.20, 'sqrt', 0, 0.2),
        effect('homelessness', -0.10, 'sqrt', 2, 0.4),
      ],
      { social: 0.5, economic: 0.3 },
    ),

    policy(
      'hospital_funding',
      'Hospital Funding',
      'Hospitals',
      'Federal contributions to state-run public hospitals. Covers infrastructure, staffing levels, medical equipment, and emergency departments. Hospital wait times are a perennial political battleground.',
      'health',
      '\u{1F3E5}',
      'Minimal',
      'Maximum',
      0.55,
      90,
      2,
      [
        effect('health_quality', 0.35, 'sqrt', 1, 0.3),
        effect('public_debt', 0.18, 'linear', 0, 0.1),
        effect('healthcare_crisis', -0.30, 'sqrt', 1, 0.4),
        effect('healthcare_workers', 0.40, 'linear', 0, 0.1),
        effect('retirees', 0.20, 'sqrt', 0, 0.2),
        effect('parents', 0.10, 'sqrt', 0, 0.2),
      ],
      { social: 0.3, economic: 0.4 },
    ),

    policy(
      'preventive_health',
      'Preventive Health Programs',
      'Prevention',
      'Funding for vaccination campaigns, cancer screenings, anti-smoking campaigns, nutrition programs, and public health education. Saves money long-term but costs upfront with delayed visible results.',
      'health',
      '\u{1F48A}',
      'None',
      'Comprehensive',
      0.35,
      25,
      3,
      [
        effect('health_quality', 0.20, 'sqrt', 2, 0.4),
        effect('public_debt', 0.05, 'linear', 0, 0.1),
        effect('obesity_epidemic', -0.30, 'sqrt', 3, 0.5),
        effect('healthcare_crisis', -0.10, 'sqrt', 3, 0.5),
        effect('parents', 0.15, 'sqrt', 0, 0.2),
        effect('students', 0.10, 'sqrt', 0, 0.3),
      ],
      { social: 0.3, economic: 0.2 },
    ),

    // ================================================================
    // EDUCATION POLICIES (4)
    // Investment in human capital. Slow to show results but
    // essential for long-term growth, equality, and innovation.
    // Students and parents are direct beneficiaries.
    // ================================================================

    policy(
      'school_funding',
      'School Funding',
      'Schools',
      'Federal funding for public and private schools. The Gonski reforms aimed to tie funding to student need rather than postcode. A key equity issue with debates over public vs private school funding ratios.',
      'education',
      '\u{1F3EB}',
      'Minimal',
      'Maximum',
      0.55,
      70,
      2,
      [
        effect('education_quality', 0.40, 'sqrt', 2, 0.4),
        effect('equality', 0.20, 'sqrt', 2, 0.4),
        effect('public_debt', 0.15, 'linear', 0, 0.1),
        effect('crime_rate', -0.10, 'sqrt', 3, 0.5),
        effect('students', 0.35, 'linear', 0, 0.1),
        effect('parents', 0.30, 'sqrt', 0, 0.2),
        effect('indigenous', 0.15, 'sqrt', 1, 0.3),
      ],
      { social: 0.3, economic: 0.4 },
    ),

    policy(
      'university_subsidies',
      'University Subsidies',
      'Uni Fund',
      'Government subsidies for university tuition through the HECS-HELP loan system. Determines the cost of higher education and accessibility for students from all backgrounds. International education is a major export.',
      'education',
      '\u{1F393}',
      'Full Fees',
      'Free University',
      0.45,
      55,
      2,
      [
        effect('education_quality', 0.25, 'sqrt', 2, 0.4),
        effect('technology_level', 0.15, 'sqrt', 3, 0.5),
        effect('public_debt', 0.12, 'linear', 0, 0.1),
        effect('equality', 0.15, 'sqrt', 2, 0.4),
        effect('students', 0.55, 'linear', 0, 0.1),
        effect('brain_drain', -0.20, 'sqrt', 2, 0.4),
        effect('education_export_boom', 0.15, 'threshold', 3, 0.5),
      ],
      { social: 0.4, economic: 0.5 },
    ),

    policy(
      'tafe_funding',
      'TAFE & Vocational Training',
      'TAFE',
      'Funding for Technical and Further Education institutions. Provides vocational qualifications essential for trades, aged care, and the service sector. Often overlooked compared to universities despite critical economic importance.',
      'education',
      '\u{1F527}',
      'Minimal',
      'Maximum',
      0.40,
      40,
      2,
      [
        effect('education_quality', 0.15, 'sqrt', 1, 0.3),
        effect('unemployment', -0.15, 'sqrt', 2, 0.4),
        effect('public_debt', 0.08, 'linear', 0, 0.1),
        effect('workers', 0.25, 'sqrt', 1, 0.3),
        effect('students', 0.25, 'sqrt', 0, 0.2),
        effect('healthcare_workers', 0.10, 'sqrt', 2, 0.4),
        effect('technology_level', 0.08, 'sqrt', 2, 0.4),
      ],
      { social: 0.2, economic: 0.3 },
    ),

    policy(
      'research_grants',
      'Research Grants',
      'Research',
      'Competitive research grants through the ARC, NHMRC, and CSIRO. Funds fundamental and applied research in universities and government labs. Vital for innovation, scientific leadership, and attracting global talent.',
      'education',
      '\u{1F4DA}',
      'None',
      'Generous',
      0.40,
      35,
      3,
      [
        effect('technology_level', 0.30, 'sqrt', 3, 0.5),
        effect('education_quality', 0.15, 'sqrt', 2, 0.4),
        effect('public_debt', 0.07, 'linear', 0, 0.1),
        effect('gdp_growth', 0.10, 'sqrt', 4, 0.5),
        effect('tech_workers', 0.25, 'sqrt', 1, 0.3),
        effect('brain_drain', -0.20, 'sqrt', 2, 0.4),
        effect('tech_boom', 0.15, 'threshold', 4, 0.5),
      ],
      { social: 0.2, economic: 0.1 },
    ),

    // ================================================================
    // LAW & ORDER POLICIES (5)
    // Security and justice. Popular with conservative voters but
    // can alienate minorities and civil liberties advocates.
    // Funding trade-offs between policing and rehabilitation.
    // ================================================================

    policy(
      'police_funding',
      'Police Funding',
      'Police',
      'Funding for state and federal police forces. Covers officer numbers, equipment, training, forensics, and community policing programs. Balances public safety against concerns about over-policing and civil liberties.',
      'law_order',
      '\u{1F46E}',
      'Minimal',
      'Maximum',
      0.50,
      55,
      1,
      [
        effect('crime_rate', -0.30, 'sqrt', 1, 0.3),
        effect('public_debt', 0.12, 'linear', 0, 0.1),
        effect('crime_wave', -0.25, 'sqrt', 1, 0.4),
        effect('workers', 0.05, 'sqrt', 0, 0.3),
        effect('religious', 0.15, 'sqrt', 0, 0.2),
        effect('indigenous', -0.15, 'sqrt', 0, 0.2),
        effect('immigrants', -0.08, 'sqrt', 0, 0.3),
      ],
      { social: -0.4, economic: -0.1 },
    ),

    policy(
      'prison_funding',
      'Prison & Corrections',
      'Prisons',
      'Funding for the prison system including incarceration, rehabilitation programs, parole services, and community corrections. Australia has rising incarceration rates with a grossly disproportionate impact on Indigenous Australians.',
      'law_order',
      '\u{1F512}',
      'Minimal',
      'Maximum',
      0.40,
      35,
      2,
      [
        effect('crime_rate', -0.15, 'sqrt', 1, 0.3),
        effect('public_debt', 0.08, 'linear', 0, 0.1),
        effect('crime_wave', -0.10, 'sqrt', 2, 0.4),
        effect('equality', -0.10, 'linear', 0, 0.3),
        effect('religious', 0.10, 'sqrt', 0, 0.2),
        effect('indigenous', -0.25, 'linear', 0, 0.2),
      ],
      { social: -0.5, economic: -0.1 },
    ),

    policy(
      'border_security',
      'Border Security',
      'Borders',
      'Funding for border protection operations including the Australian Border Force, maritime surveillance, offshore processing, and detention centres. One of the most divisive and emotionally charged issues in Australian politics.',
      'law_order',
      '\u{1F6A7}',
      'Open Borders',
      'Fortress Australia',
      0.55,
      40,
      1,
      [
        effect('crime_rate', -0.05, 'sqrt', 1, 0.3),
        effect('international_relations', -0.15, 'linear', 0, 0.2),
        effect('public_debt', 0.08, 'linear', 0, 0.1),
        effect('immigration_crisis', -0.25, 'sqrt', 1, 0.3),
        effect('religious', 0.25, 'sqrt', 0, 0.2),
        effect('immigrants', -0.40, 'linear', 0, 0.1),
        effect('environmentalists', -0.10, 'sqrt', 0, 0.3),
      ],
      { social: -0.7, economic: -0.2 },
    ),

    policy(
      'counter_terrorism',
      'Counter-Terrorism',
      'Anti-Terror',
      'Intelligence and counter-terrorism funding through ASIO, AFP, and the Australian Signals Directorate. Includes surveillance capabilities, community deradicalisation programs, and emergency response.',
      'law_order',
      '\u{1F6E1}\u{FE0F}',
      'Minimal',
      'Maximum',
      0.45,
      30,
      1,
      [
        effect('crime_rate', -0.08, 'threshold', 0, 0.2),
        effect('international_relations', 0.05, 'sqrt', 1, 0.3),
        effect('public_debt', 0.06, 'linear', 0, 0.1),
        effect('technology_level', 0.05, 'sqrt', 2, 0.4),
        effect('immigrants', -0.15, 'sqrt', 0, 0.3),
        effect('religious', 0.10, 'sqrt', 0, 0.3),
        effect('tech_workers', -0.05, 'sqrt', 0, 0.3),
      ],
      { social: -0.5, economic: -0.2 },
    ),

    policy(
      'legal_aid',
      'Legal Aid Funding',
      'Legal Aid',
      'Government-funded legal assistance for people who cannot afford private representation. Essential for justice system fairness but chronically underfunded, leaving many Australians without adequate legal support.',
      'law_order',
      '\u{2696}\u{FE0F}',
      'None',
      'Comprehensive',
      0.35,
      20,
      1,
      [
        effect('equality', 0.15, 'sqrt', 0, 0.2),
        effect('crime_rate', -0.05, 'sqrt', 1, 0.3),
        effect('public_debt', 0.04, 'linear', 0, 0.1),
        effect('indigenous', 0.20, 'sqrt', 0, 0.2),
        effect('immigrants', 0.15, 'sqrt', 0, 0.2),
        effect('workers', 0.05, 'sqrt', 0, 0.3),
      ],
      { social: 0.5, economic: 0.2 },
    ),

    // ================================================================
    // INFRASTRUCTURE POLICIES (5)
    // Long-term capital investment. Slow to build, expensive, but
    // essential for productivity and quality of life. Trade-offs
    // between roads (motorists) and transit (environmentalists).
    // ================================================================

    policy(
      'road_funding',
      'Road & Highway Funding',
      'Roads',
      'Federal funding for the national highway network, bridges, and urban road upgrades. Critical given Australia\'s vast distances and car-dependent suburban development patterns.',
      'infrastructure',
      '\u{1F6E3}\u{FE0F}',
      'Minimal',
      'Maximum',
      0.55,
      65,
      2,
      [
        effect('infrastructure_quality', 0.25, 'sqrt', 2, 0.4),
        effect('gdp_growth', 0.10, 'sqrt', 2, 0.4),
        effect('public_debt', 0.14, 'linear', 0, 0.1),
        effect('environment_quality', -0.10, 'linear', 1, 0.3),
        effect('motorists', 0.50, 'linear', 0, 0.1),
        effect('farmers', 0.15, 'sqrt', 1, 0.3),
        effect('business_owners', 0.10, 'sqrt', 1, 0.3),
      ],
      { social: -0.2, economic: -0.2 },
    ),

    policy(
      'public_transport',
      'Public Transport Investment',
      'Transit',
      'Federal investment in urban rail, metro, bus rapid transit, and light rail networks. Reduces congestion, cuts emissions, and provides essential mobility for those without cars.',
      'infrastructure',
      '\u{1F68A}',
      'Minimal',
      'World Class',
      0.40,
      70,
      3,
      [
        effect('infrastructure_quality', 0.20, 'sqrt', 2, 0.4),
        effect('environment_quality', 0.15, 'sqrt', 2, 0.4),
        effect('public_debt', 0.15, 'linear', 0, 0.1),
        effect('gdp_growth', 0.08, 'sqrt', 3, 0.5),
        effect('workers', 0.20, 'sqrt', 1, 0.3),
        effect('students', 0.20, 'sqrt', 1, 0.3),
        effect('environmentalists', 0.25, 'sqrt', 0, 0.2),
        effect('motorists', -0.10, 'linear', 0, 0.3),
      ],
      { social: 0.3, economic: 0.2 },
    ),

    policy(
      'nbn_internet',
      'NBN & Digital Infrastructure',
      'NBN',
      'The National Broadband Network and digital infrastructure rollout. A multi-billion dollar project plagued by political interference over technology choices (FTTP vs FTTN). Essential for a modern digital economy and regional connectivity.',
      'infrastructure',
      '\u{1F4F6}',
      'Neglected',
      'World Class',
      0.45,
      50,
      3,
      [
        effect('technology_level', 0.30, 'sqrt', 2, 0.4),
        effect('gdp_growth', 0.12, 'sqrt', 3, 0.5),
        effect('public_debt', 0.12, 'linear', 0, 0.1),
        effect('infrastructure_quality', 0.15, 'sqrt', 2, 0.4),
        effect('tech_workers', 0.35, 'sqrt', 1, 0.3),
        effect('business_owners', 0.15, 'sqrt', 2, 0.4),
        effect('farmers', 0.10, 'sqrt', 2, 0.4),
        effect('tech_boom', 0.15, 'threshold', 3, 0.5),
      ],
      { social: 0.1, economic: 0.1 },
    ),

    policy(
      'water_infrastructure',
      'Water Infrastructure',
      'Water',
      'Investment in dams, desalination plants, water recycling facilities, and the Murray-Darling Basin Plan. Existentially important for a drought-prone continent facing increasing climate variability.',
      'infrastructure',
      '\u{1F4A7}',
      'Minimal',
      'Maximum',
      0.40,
      45,
      3,
      [
        effect('infrastructure_quality', 0.15, 'sqrt', 2, 0.4),
        effect('environment_quality', 0.10, 'sqrt', 2, 0.4),
        effect('public_debt', 0.10, 'linear', 0, 0.1),
        effect('drought', -0.30, 'sqrt', 2, 0.5),
        effect('farmers', 0.35, 'sqrt', 1, 0.3),
        effect('indigenous', 0.10, 'sqrt', 1, 0.3),
        effect('bushfire', -0.08, 'sqrt', 2, 0.5),
      ],
      { social: 0.1, economic: 0.1 },
    ),

    policy(
      'renewable_energy',
      'Renewable Energy Investment',
      'Renewables',
      'Federal investment in solar, wind, battery storage, and pumped hydro. Includes the Renewable Energy Target, Clean Energy Finance Corporation, and grid modernisation. Australia has immense solar and wind potential.',
      'infrastructure',
      '\u{2600}\u{FE0F}',
      'None',
      'Full Transition',
      0.35,
      60,
      3,
      [
        effect('environment_quality', 0.30, 'sqrt', 2, 0.4),
        effect('technology_level', 0.15, 'sqrt', 2, 0.4),
        effect('public_debt', 0.13, 'linear', 0, 0.1),
        effect('gdp_growth', 0.08, 'sqrt', 3, 0.5),
        effect('climate_emergency', -0.25, 'sqrt', 3, 0.5),
        effect('environmentalists', 0.55, 'linear', 0, 0.1),
        effect('tech_workers', 0.15, 'sqrt', 1, 0.3),
        effect('motorists', -0.05, 'linear', 0, 0.3),
        effect('green_transition', 0.30, 'sqrt', 2, 0.4),
      ],
      { social: 0.5, economic: 0.3 },
    ),

    // ================================================================
    // ENVIRONMENT POLICIES (4)
    // Protecting Australia's unique biodiversity and managing
    // climate change. Popular with environmentalists and young
    // voters, resisted by some business and farming interests.
    // ================================================================

    policy(
      'conservation_funding',
      'Conservation & Biodiversity',
      'Conservation',
      'Funding to protect Australia\'s unique and threatened biodiversity. Covers threatened species programs, land clearing restrictions, habitat restoration, and Great Barrier Reef protection.',
      'environment',
      '\u{1F998}',
      'None',
      'Maximum',
      0.35,
      25,
      2,
      [
        effect('environment_quality', 0.30, 'sqrt', 1, 0.3),
        effect('public_debt', 0.05, 'linear', 0, 0.1),
        effect('tourism_boom', 0.10, 'sqrt', 2, 0.4),
        effect('environmentalists', 0.50, 'linear', 0, 0.1),
        effect('indigenous', 0.15, 'sqrt', 0, 0.2),
        effect('farmers', -0.10, 'linear', 0, 0.3),
      ],
      { social: 0.5, economic: 0.2 },
    ),

    policy(
      'emissions_standards',
      'Emissions Standards',
      'Emissions',
      'Regulations on vehicle and industrial emissions. Australia has historically lagged well behind other developed nations on vehicle emission standards, only recently introducing fuel efficiency rules.',
      'environment',
      '\u{1F4A8}',
      'Unregulated',
      'Strictest',
      0.35,
      10,
      2,
      [
        effect('environment_quality', 0.25, 'sqrt', 2, 0.4),
        effect('health_quality', 0.08, 'sqrt', 2, 0.4),
        effect('gdp_growth', -0.05, 'linear', 1, 0.3),
        effect('climate_emergency', -0.15, 'sqrt', 2, 0.5),
        effect('environmentalists', 0.40, 'linear', 0, 0.1),
        effect('motorists', -0.30, 'linear', 0, 0.2),
        effect('business_owners', -0.15, 'linear', 0, 0.2),
        effect('green_transition', 0.15, 'sqrt', 2, 0.4),
      ],
      { social: 0.4, economic: 0.3 },
    ),

    policy(
      'national_parks',
      'National Parks & Reserves',
      'Parks',
      'Funding and expansion of the national park and nature reserve system. Protects wilderness areas, supports tourism, and preserves Indigenous cultural heritage sites and sacred lands.',
      'environment',
      '\u{1F3DE}\u{FE0F}',
      'Minimal',
      'Expansive',
      0.40,
      20,
      2,
      [
        effect('environment_quality', 0.20, 'sqrt', 1, 0.3),
        effect('public_debt', 0.04, 'linear', 0, 0.1),
        effect('tourism_boom', 0.15, 'sqrt', 2, 0.4),
        effect('environmentalists', 0.35, 'linear', 0, 0.1),
        effect('indigenous', 0.20, 'sqrt', 0, 0.2),
        effect('farmers', -0.08, 'sqrt', 0, 0.3),
        effect('bushfire', -0.05, 'inverse', 1, 0.4),
      ],
      { social: 0.3, economic: 0.1 },
    ),

    policy(
      'recycling_programs',
      'Waste & Recycling Programs',
      'Recycling',
      'Container deposit schemes, recycling infrastructure investment, and waste reduction targets. Includes bans on single-use plastics, e-waste programs, and circular economy initiatives.',
      'environment',
      '\u{267B}\u{FE0F}',
      'None',
      'Comprehensive',
      0.35,
      15,
      2,
      [
        effect('environment_quality', 0.15, 'sqrt', 1, 0.3),
        effect('public_debt', 0.03, 'linear', 0, 0.1),
        effect('technology_level', 0.05, 'sqrt', 2, 0.4),
        effect('environmentalists', 0.30, 'linear', 0, 0.1),
        effect('parents', 0.10, 'sqrt', 0, 0.2),
        effect('business_owners', -0.08, 'linear', 0, 0.3),
      ],
      { social: 0.3, economic: 0.1 },
    ),

    // ================================================================
    // FOREIGN POLICIES (4)
    // Australia's place in the world. Defence, diplomacy, and
    // migration. The AUKUS alliance, Pacific step-up, and
    // immigration intake are defining foreign policy debates.
    // ================================================================

    policy(
      'defence_spending',
      'Defence Spending',
      'Defence',
      'Funding for the Australian Defence Force including Army, Navy, and Air Force. Covers the AUKUS nuclear submarine deal, personnel, equipment, and overseas deployments. Australia is ramping spending toward 2% of GDP.',
      'foreign',
      '\u{1F396}\u{FE0F}',
      'Minimal',
      'Maximum',
      0.45,
      120,
      2,
      [
        effect('international_relations', 0.20, 'sqrt', 1, 0.3),
        effect('public_debt', 0.25, 'linear', 0, 0.1),
        effect('technology_level', 0.10, 'sqrt', 2, 0.4),
        effect('gdp_growth', 0.05, 'sqrt', 1, 0.3),
        effect('religious', 0.15, 'sqrt', 0, 0.2),
        effect('workers', 0.05, 'sqrt', 1, 0.3),
        effect('environmentalists', -0.15, 'linear', 0, 0.2),
      ],
      { social: -0.5, economic: -0.3 },
    ),

    policy(
      'foreign_aid',
      'Foreign Aid',
      'Aid',
      'Official development assistance to developing nations, particularly in the Pacific Islands and Southeast Asia. Australia\'s aid budget has been declining as a proportion of GNI, drawing criticism from humanitarian organisations.',
      'foreign',
      '\u{1F30F}',
      'None',
      'Generous',
      0.35,
      30,
      1,
      [
        effect('international_relations', 0.25, 'sqrt', 1, 0.3),
        effect('public_debt', 0.06, 'linear', 0, 0.1),
        effect('environmentalists', 0.10, 'sqrt', 0, 0.3),
        effect('religious', 0.10, 'sqrt', 0, 0.3),
        effect('immigrants', 0.10, 'sqrt', 0, 0.3),
        effect('immigration_crisis', -0.05, 'sqrt', 2, 0.5),
      ],
      { social: 0.4, economic: 0.2 },
    ),

    policy(
      'immigration_level',
      'Immigration Intake',
      'Immigration',
      'The annual permanent migration program intake. Covers skilled migration, family reunion, and special eligibility visas. A highly charged topic affecting housing demand, wages, cultural identity, and economic growth.',
      'foreign',
      '\u{1F6EB}',
      'Near Zero',
      'Very High',
      0.50,
      5,
      2,
      [
        effect('gdp_growth', 0.20, 'sqrt', 1, 0.3),
        effect('housing_affordability', -0.20, 'linear', 1, 0.3),
        effect('unemployment', 0.08, 'sqrt', 1, 0.3),
        effect('consumer_confidence', 0.05, 'linear', 1, 0.3),
        effect('workers', -0.10, 'linear', 0, 0.2),
        effect('business_owners', 0.15, 'sqrt', 0, 0.2),
        effect('immigrants', 0.30, 'sqrt', 0, 0.2),
        effect('religious', -0.10, 'sqrt', 0, 0.3),
        effect('housing_crisis', 0.15, 'threshold', 2, 0.4),
        effect('immigration_crisis', -0.10, 'inverse', 1, 0.3),
      ],
      { social: 0.2, economic: -0.1 },
    ),

    policy(
      'refugee_intake',
      'Refugee & Humanitarian Intake',
      'Refugees',
      'The annual humanitarian visa allocation for refugees and asylum seekers. An intensely polarising issue since the Tampa affair and subsequent "Stop the Boats" campaigns. Intersects with border security and international obligations.',
      'foreign',
      '\u{1F91D}',
      'None',
      'Generous',
      0.35,
      15,
      1,
      [
        effect('international_relations', 0.15, 'sqrt', 0, 0.2),
        effect('public_debt', 0.04, 'linear', 0, 0.1),
        effect('equality', 0.05, 'sqrt', 1, 0.3),
        effect('immigrants', 0.35, 'sqrt', 0, 0.2),
        effect('environmentalists', 0.15, 'sqrt', 0, 0.2),
        effect('religious', -0.20, 'linear', 0, 0.2),
        effect('workers', -0.05, 'sqrt', 0, 0.3),
        effect('immigration_crisis', 0.10, 'threshold', 1, 0.4),
      ],
      { social: 0.7, economic: 0.1 },
    ),

  ];
}
